<?php

/**
 * BaseMenu
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $menu_id
 * @property string $nombre
 * @property string $descripcion
 * @property string $url
 * @property integer $nivel
 * @property integer $codigo_padre
 * @property integer $orden
 * @property string $acl_visualizacion
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
abstract class Model_Base_Menu extends Doctrine_Record
{
	protected $_primary_key;

	public function setPrimaryKey($id_name){
		$this->_primary_key = $id_name;
	}
	public function getPrimaryKey(){
		return $this->_primary_key;
	}
	public function setTableDefinition()
	{
		$this->setTableName('menu');
		
		
		$this->hasColumn('menu_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'primary' => true,
        	 'autoincrement' => true,
		));
		$this->hasColumn('menu', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             'fixed' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
		));

		$this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             'fixed' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
		));

		$this->hasColumn('padre_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
		));
		$this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
		));
			

	}

}