<?php
/**
 * BaseMotivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $motivo_id
 * @property string $motivo
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
abstract class Model_Base_Motivo extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('motivo');
        $this->hasColumn('motivo_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('motivo', 'string', 250, array(
             'type' => 'string',
             'length' => '250',
             'fixed' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));                             	
    }
}