<script type="text/javascript">
function listar(){
	
	url="./entidad/productor/list";
			$.ajax({url: url,
		        success:function(result){
		        $('#content').html(result);
		      }});
		   
		    return false;
	}

function editForm(f){

    var url = f.action;

     $.ajax({url: url,
        data:{id: f.id.value 
            ,nombre: f.nombre.value
            ,matricula: f.matricula.value
            ,cuit: f.cuit.value
            ,domicilio: f.domicilio.value
            ,codigo_postal: f.codigo_postal.value
            ,provincia: f.provincia.value
            ,localidad: f.localidad.value
            ,telefono: f.telefono.value
            ,email: f.email.value
            ,ingresos_brutos: f.ingresos_brutos.value
            ,jubilacion: f.jubilacion.value
            ,situacion_iva: f.situacion_iva.value
            ,situacion_juridica: f.situacion_juridica.value
            }
        , success:function(result){
        $('#content').html(result);
      }});
   
   
    return false;
}
</script>



<form action="./entidad/productor/edit"  onSubmit="return editForm(this)">
<table>
<tr><td>productor_id</td><td><input type="text" name="id" value="<?=$this->row['productor_id']?>"></input></td></tr>
<tr><td>Nombre</td><td><input type="text" name="nombre" value="<?=$this->row['nombre']?>"></input></td></tr>
<tr><td>Matricula</td><td><input type="text" name="matricula" value="<?=$this->row['matricula']?>"></input></td></tr>
<tr><td>CUIT</td><td><input type="text" name="cuit" value="<?=$this->row['cuit']?>"></input></td></tr>
<tr><td>Domicilio</td><td><input type="text" name="domicilio" value="<?=$this->row['domicilio']?>"></input></td></tr>
<tr><td>Codigo Postal</td><td><input type="text" name="codigo_postal" value="<?=$this->row['codigo_postal']?>"></input></td></tr>
<tr><td>Provincia</td><td><input type="text" name="provincia" value="<?=$this->row['provincia']?>"></input></td></tr>
<tr><td>Localidad</td><td><input type="text" name="localidad" value="<?=$this->row['localidad']?>"></input></td></tr>
<tr><td>Telefono</td><td><input type="text" name="telefono" value="<?=$this->row['telefono']?>"></input></td></tr>
<tr><td>Email</td><td><input type="text" name="email" value="<?=$this->row['email']?>"></input></td></tr>
<tr><td>Ingresos Brutos</td><td><input type="text" name="ingresos_brutos" value="<?=$this->row['ingresos_brutos']?>"></input></td></tr>
<tr><td>Jubilacion</td><td><input type="text" name="jubilacion" value="<?=$this->row['jubilacion']?>"></input></td></tr>
<tr><td>Situacion Iva</td><td><input type="text" name="situacion_iva" value="<?=$this->row['situacion_iva']?>"></input></td></tr>
<tr><td>Situacion Juridica</td><td><input type="text" name="situacion_juridica" value="<?=$this->row['situacion_juridica']?>"></input></td></tr>

<tr><td></td><td><input type="submit" value="guardar"></input></td><td><input type="button" name="Cancel" onclick="return listar()" value="cancel" /></input></td></tr>
</table>
</form>
