<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"; "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Zend Framework Default Application</title>
</head>
<body>
<h1>TOKEN INVALIDO!</h1>
<h2><?php echo $this->message ?></h2>
<h3>modulo: <?php echo $this->escape($this->modulo)?></h3>
<h3>controlador: <?php echo $this->escape($this->controlador)?></h3>
<h3>accion: <?php echo $this->escape($this->accion)?></h3>
<div><a href="/">Volver a Pagina Principal</a></div>
</body>
</html>
