<script type="text/javascript">

function listarDespachanteAduana(){
	
	url="./entidad/despachante-aduana/list";

	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       
	
			$.ajax({url: url,
		        success:function(result){
		        $(href).html(result);
		      }});
		   
		    return false;
	}
function addDespachanteAduana(f){

	var url = f.action;

	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       

    $.ajax({url: url,
        data:{
        	add: f.add.value
             ,id: f.id.value 
            ,nombre: f.nombre.value
            ,cuit: f.cuit.value
            ,domicilio: f.domicilio.value
            ,codigo_postal: f.codigo_postal.value
            ,localidad: f.localidad.value
            ,provincia: f.provincia.value
            ,telefono: f.telefono.value
            ,email: f.email.value
            ,fecha_nacimiento: f.fecha_nacimiento.value
            }
        , success:function(result){
        $(href).html(result);
      }});
	   
	   
	    return false;
	}

</script>
<form action="./entidad/despachante-aduana/add"
	onSubmit="return addDespachanteAduana(this)">
	<input type="hidden" name="add" value="1"></input>
	<table>
		<tr>
			<td>despachante_aduana_id</td>
			<td><input readonly type="text" name="id"
				value="<?=$this->row['despachante_aduana_id']?>"></input></td>
		</tr>
		<tr>
			<td>Nombre</td>
			<td><input type="text" name="nombre"
				value="<?=$this->row['nombre']?>"></input></td>
		</tr>
		<tr>
			<td>CUIT</td>
			<td><input type="text" name="cuit" value="<?=$this->row['cuit']?>"></input>
			</td>
		</tr>
		<tr>
			<td>Domicilio</td>
			<td><input type="text" name="domicilio"
				value="<?=$this->row['domicilio']?>"></input></td>
		</tr>
		<tr>
			<td>Codigo Postal</td>
			<td><input type="text" name="codigo_postal"
				value="<?=$this->row['codigo_postal']?>"></input></td>
		</tr>
		<tr>
			<td>Provincia</td>
			<td><input type="text" name="provincia"
				value="<?=$this->row['provincia']?>"></input></td>
		</tr>
		<tr>
			<td>Localidad</td>
			<td><input type="text" name="localidad"
				value="<?=$this->row['localidad']?>"></input></td>
		</tr>
		<tr>
			<td>Telefono</td>
			<td><input type="text" name="telefono"
				value="<?=$this->row['telefono']?>"></input></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="email" value="<?=$this->row['email']?>"></input>
			</td>
		</tr>
		<tr>
			<td>Fecha Nacimiento</td>
			<td><input type="text" name="fecha_nacimiento"
				value="<?=$this->row['fecha_nacimiento']?>"></input></td>
		</tr>

		<tr>
			<td></td>
			<td><input type="submit" value="guardar"></input></td>
			<td><input type="button" name="Cancel"
				onclick="return listarDespachanteAduana()" value="cancel" /></input></td>
		</tr>
	</table>
</form>
