
<script type="text/javascript">
function listPaginator(g){

	var url = $(g).attr('url')
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;       
	var url = $(g).attr('href')

	    $.ajax({url: url,success:function(result){
	        $(href).html(result);
	      }});
	   
	    return false;
	}
	
function despachanteAduana(f){
	var url = $(f).attr('url');
	if(url == null){
		url="./entidad/despachante-aduana/list";
	}
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       

	    $.ajax({url: url,success:function(result){
	        $(href).html(result);
	      }});

	    return false;
	}

function listAgente(f){
	var url = f.action;
	
	
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       

	    $.ajax({url: url
		    ,data:{
			    criterio:f.criterio.value
			    }
		    ,success:function(result){
	        $(href).html(result);
	      }});

	    return false;
	}

</script>

<form action="./entidad/despachante-aduana/list" onSubmit="return listAgente(this)">

	<table id="buscar_despachante-aduana">
		<tr>
			<td>Buscar:</td>
			<td><input type="text" name="criterio" /></td>
		
		
			<td><input type="submit" name="buscar" value="buscar"></input></td>
		</tr>
	</table>
</form>
<hr>
<table class="ui-widget">
	<thead class="ui-widget-header">
  <tr>
    <th>despachante_aduana_id</th>
    <th>Nombre</th>
    <th>CUIT</th>
    <th>Domicilio</th>
    <th>Codigo Postal</th>
    <th>Provincia</th>
    <th>Localidad</th>
    <th>Telefono</th>
    <th>Email</th>
    <th>Fecha Nacimiento</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody class="ui-widget-content">
<?foreach($this->rows as $row):?>
  <tr>
  <td><?=$row['despachante_aduana_id'] ?></td>
    <td><?=$row['nombre'] ?></td>
    <td><?=$row['cuit'] ?></td>
    <td><?=$row['domicilio'] ?></td>
    <td><?=$row['codigo_postal'] ?></td>
    <td><?=$row['provincia'] ?></td>
    <td><?=$row['localidad'] ?></td>
    <td><?=$row['telefono'] ?></td>
    <td><?=$row['email'] ?></td>
    <td><?=$row['fecha_nacimiento'] ?></td>
    <td><input type="button" value="Ver" url="./entidad/despachante-aduana/view/id/<?=$row['despachante_aduana_id']?>" onClick="return despachanteAduana(this)"> </input> </td>
    <td><input type="button" value="Eliminar" url="./entidad/despachante-aduana/delete/id/<?=$row['despachante_aduana_id']?>" onClick="return despachanteAduana(this)"> </input> </td>
  </tr>

<?endforeach;?>
<tr>
    <td><input type="button" value="Agregar" url="./entidad/despachante-aduana/add/" onClick="return despachanteAduana(this)"> </input> </td>
  </tr>
  </tbody>
</table>
<?= $this->paginationControl($this->rows, 'Sliding', 'paginator.phtml',array('criterio'=>$this->criterio)); ?>

