<script type="text/javascript">
function listar(){
	
	url="./entidad/entidad/list";
			$.ajax({url: url,
		        success:function(result){
		        $('#content').html(result);
		      }});
		   
		    return false;
	}

function editForm(f){

    //console.debug(f.nombre.value);
    //console.debug(f.apellido.value);

    var url = f.action;
    $.ajax({url: url,
        data:{id:f.id.value ,nombre: f.nombre.value,apellido: f.apellido.value}
        , success:function(result){
        $('#content').html(result);
      }});
   
    return false;
}
</script>

<form action="./entidad/entidad/edit"  onSubmit="return editForm(this)">
<input type="text" name="id" value="<?=$this->entidad['entidad_id'] ?>"></input>
<input type="text" name="nombre" value="<?=$this->entidad['nombre'] ?>"></input>
<input type="text" name="apellido" value="<?=$this->entidad['apellido'] ?>"></input>
<input type="submit" value="guardar"></input>
<input type="button" name="Cancel" onclick="return listar()" value="cancel" /></input>

</form>
