<?php //echo $this->headScript()->appendFile('./js/gseguros.operaciones.deuda-asegurado.js');?>
<script type="text/javascript">

function printContent(div_id)
{
var DocumentContainer = document.getElementById(div_id);
var html = '<html><head>'+
               '<link href="css/template.css" rel="stylesheet" type="text/css" />'+
               '</head><body style="background:#ffffff;">'+
               DocumentContainer.innerHTML+
               '</body></html>';

    var WindowObject = window.open("", "PrintWindow",
    "width=750,height=650,top=50,left=50,toolbars=no,scrollbars=yes,status=no,resizable=yes");
    WindowObject.document.writeln(html);
    WindowObject.document.close();
    WindowObject.focus();
    WindowObject.print();
    WindowObject.close();
    document.getElementById('print_link').style.display='block';
}



$(document).ready(
		function(){

	var id_check = 0;
	var moneda_distinta = false;		
	var importe_total_a_pagar = 0;		
	var array_polizas = new Array(); 
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');
	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	
	var href = $(tab).attr('href') ;
	
	var table = href+' #div_resultado_busqueda'


	//Cheques
	$("#div_form_cheques_show,#datos_pago_show").hover(
		  function () {
		    $(this).append($("<span> (Clic para mostrar u ocultar)</span>"));
		  }, 
		  function () {
		    $(this).find("span:last").remove();
		  }
		);


	$('#div_form_cheques').hide();

	$('#datos_pago_show').click(function() {
		$('#datos_pago').toggle();
	});

	$('#div_form_cheques_show').click(function() {
		$('#div_form_cheques').toggle();
	});
	
	//FIN Cheques
	
	$('#fecha_pago').datepicker(
		{
			dateFormat : 'yy-mm-dd',
			dayNamesMin : [ 'Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa' ],
			monthNames : [ 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo',
					'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
					'Noviembre', 'Diciembre' ]
		});
	//Oculto formulario de pago
	
	$('#realizar_pago_show').hide();

	
	$('#buscar_poliza_deuda_asegurado').click(function(){

		//alert('clic	');
		var nro_poliza = $('#nro_poliza').val();
		var asegurado_id = $('#asegurado_id').val();
		//var data = $('#form_busqueda_poliza').serializeArray();
		//var url = $('#').val();
		//alert(nro_poliza);

		$.ajax({
		    url: './operaciones/deuda-asegurado/buscar-poliza-deuda-asegurado/'
			,data:{nro_poliza:nro_poliza,asegurado_id:asegurado_id}
			,success:function(result){
	        ////console.debug(result);
	        $(table).html(result);
	      	}
	      });
		
		});
	
//imprimir listado de las polizas a pagar
$('#iimprimir_listado_pago').click(function(e) {

	e.preventDefault();

	var array_polizas = new Array();

	$('#div_tabla_polizas input').each(function(){
		
		if(!( $(this).hasClass('eliminar_poliza') )){
		  //Agrego los id de las polizas a modificar	
		  array_polizas.push($(this).val());
		}
	});

	//console.debug(array_polizas);

var url = "./operaciones/deuda-asegurado/imprimir-listado-poliza-deuda";
	//envio los id para realizar la impresion
	$.ajax({
		
	    url: url,
		data:{
	    	 array_polizas: array_polizas.toString()
	         }

		    ,success:function(result){
		    	window.open('./operaciones/deuda-asegurado/imprimir-listado-poliza-deuda/');
			console.debug(result);    
	    	//$(href).html(result);
	  		}
	  });
	
});


	
	//Realizar Pago
$('#realizar_pago').click(function() {
	$('#realizar_pago_show').toggle();

	//Recorro la tabla para completar el campo importe en efectivo

	$('#div_tabla_polizas input').each(function(){

		if(!( $(this).hasClass('eliminar_poliza') )){
			
		  importe_total_a_pagar = importe_total_a_pagar + parseFloat($(this).attr('importe'));
		}
	});

	$('#importe').val(importe_total_a_pagar);

	//console.debug('importe_total_a_pagar:'+importe_total_a_pagar);
	
	
});
	
// Guardar Solicitud
$('#confirmar_pago').click(function() {
//alert('realiza el pago de las polizas seleccionadas');
	
	//alert('dentro de click function');
	var importe = $('#importe'),
    moneda_id = $('#moneda_id'),
    asegurado_id = $('#asegurado_id'),
    fecha_pago = $('#fecha_pago');
	importe_cheque_0 = $('#importe_cheque_0'),
	importe_cheque_1 = $('#importe_cheque_1'),
	importe_cheque_2 = $('#importe_cheque_2'),
	importe_cheque_3 = $('#importe_cheque_3'),
	importe_cheque_4 = $('#importe_cheque_4'),
	importe_cheque_5 = $('#importe_cheque_5'),
	nro_cheque_0 = $('#nro_cheque_0'),
	nro_cheque_1 = $('#nro_cheque_1'),
	nro_cheque_2 = $('#nro_cheque_2'),
	nro_cheque_3 = $('#nro_cheque_3'),
	nro_cheque_4 = $('#nro_cheque_4'),
	nro_cheque_5 = $('#nro_cheque_5'),
	banco_cheque_0 = $('#banco_cheque_0'),
	banco_cheque_1 = $('#banco_cheque_1'),
	banco_cheque_2 = $('#banco_cheque_2'),
	banco_cheque_3 = $('#banco_cheque_3'),
	banco_cheque_4 = $('#banco_cheque_4'),
	banco_cheque_5 = $('#banco_cheque_5'),
	numero_factura = $('#numero_factura'),
	cotizacion_divisa = $('#cotizacion_divisa'),
	descuento = $('#descuento');

	//var importe_total_a_pagar = 0;
		
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');
		
	// Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	// ////console.debug($('#tabs ul li a'));
	var href = $(tab).attr('href') ;
	// //console.debug(href);
	//var href_result = href+" #resultado_pago";
	////console.debug(href_t); 
		// var url = "./poliza/solicitud/confirmar-solicitud";
	var url = "./operaciones/deuda-asegurado/pagar-deuda-asegurado";
		
	var array_polizas = new Array();

		$('#div_tabla_polizas input').each(function(){

			////console.debug('compara esto:'+moneda_id.val());
			////console.debug('con esto'+$(this).attr('moneda'));
			////console.debug('tiene la clase?'+$(this).hasClass('eliminar_poliza'));
			//chequea que sean de la misma moneda, si no lo es sale		
			if(!( $(this).hasClass('eliminar_poliza') )){
				
			if(moneda_id.val() != $(this).attr('moneda')){
				alert("Debe seleccionar el mismo tipo de moneda");
				moneda_distinta = true;
				return false;
			}
			}
			if(!( $(this).hasClass('eliminar_poliza') )){
				
			  //Agrego los id de las polizas a modificar	
			  array_polizas.push($(this).val());
			}
		});


		if(moneda_distinta)return false;
		
	//console.debug(array_polizas);
	
	//return false;
		

	var data = $('#pago_poliza').serializeArray();

	var data_cheques = $('#div_form_cheques').serializeArray();
	var array_cheques = new Array();

	//Importe total que ingresa el usuario(Efectivo+Cheques)
	var importe_total = 0;
	importe_total = parseFloat(importe.val()) +	parseFloat(importe_cheque_0.val()) + 
	parseFloat(importe_cheque_1.val()) + parseFloat(importe_cheque_2.val())	
	+ parseFloat(importe_cheque_3.val()) + parseFloat(importe_cheque_4.val())
	+ parseFloat(importe_cheque_5.val());

	// alert(importe_total);
	if(importe_total != importe_total_a_pagar){
	
	var resp = confirm("El importe a pagar es diferente, desea continuar?");

	if(!resp)return false;

	}

	$('#realizar_pago_show').hide();
	
$.ajax({
	
    url: url,
	data:{
    	 array_polizas: array_polizas.toString()
    	 ,importe: importe_total
    	 ,importe_efectivo: parseFloat(importe.val())
    	 ,moneda_id: moneda_id.val()
    	 ,fecha_pago: fecha_pago.val()
    	 ,asegurado_id: asegurado_id.val()
    	 ,descuento: descuento.val()
    	 // por ahora los paso separados porque no funciona el JSON cuando paso mas de un parametro
		// pasa el array*/
    	,importe_cheque_0 :importe_cheque_0.val()
		,importe_cheque_1 : importe_cheque_1.val()
		,importe_cheque_2 : importe_cheque_2.val()
    	,importe_cheque_3 :importe_cheque_3.val()
		,importe_cheque_4 : importe_cheque_4.val()
		,importe_cheque_5 : importe_cheque_5.val()
		,nro_cheque_0 :nro_cheque_0.val()
		,nro_cheque_1 : nro_cheque_1.val()
		,nro_cheque_2 : nro_cheque_2.val()
		,nro_cheque_3 :nro_cheque_3.val()
		,nro_cheque_4 : nro_cheque_4.val()
		,nro_cheque_5 : nro_cheque_5.val()
		,banco_cheque_0 : banco_cheque_0.val()
		,banco_cheque_1 : banco_cheque_1.val()
		,banco_cheque_2 : banco_cheque_2.val()
		,banco_cheque_3 : banco_cheque_3.val()
		,banco_cheque_4 : banco_cheque_4.val()
		,banco_cheque_5 : banco_cheque_5.val()
		,cotizacion_divisa : cotizacion_divisa.val()
		,numero_factura : numero_factura.val()    	
        }

	    ,success:function(result){
    	$(href).html(result);
  		}
  });

});
//FIN Realizar pago
	});
</script>


<?php
/*1- Lista el asegurado
 2- busca la poliza a pagar
 3- la agrega a otro listado
 4- una vez que tiene todas las polizas en ese listado realiza el pago como estaba antes.
 *
 */
?>

<table>
	<tr>
		<th>Cliente:</th>
		<td><?=$this->asegurado?></td>
	</tr>
</table>

<?if(!$this->isAgente):?>
<table>
	<tr>
		<th>Moneda:</th>
		<td>Pesos</td>
		<td>Dolar</td>
		<td>Euro</td>
	</tr>
	<tr>
		<th>Debe:</th>
		<td><?=(empty($this->debe_pesos))?'0':$this->debe_pesos?></td>
		<td><?=(empty($this->debe_dolar))?'0':$this->debe_dolar?></td>
		<td><?=(empty($this->debe_euro))?'0':$this->debe_euro?></td>
	</tr>
</table>
<?endif;?>
<hr>

<form id="form_busqueda_poliza" name="form_busqueda_poliza"
	action="./operaciones/deuda-asegurado/buscar-poliza-deuda-asegurado"
	onSubmit="return false"><input type="hidden" id="asegurado_id"
	name="asegurado_id" value="<?=$this->asegurado_id?>"></input>

<div id="div_busqueda_poliza">
<table>
	<tr>
		<td>Nro Poliza:</td>
		<td><input id="nro_poliza" value="" name=""></input></td>
		<td><input type="button" id="buscar_poliza_deuda_asegurado" value="Buscar" name=""></input></td>
	</tr>
</table>
</div>
</form>
<div id="div_resultado_busqueda"></div>


<div id="div_tabla_polizas">
<hr>
<table class="ui-widget" id="deuda_tabla_polizas">
	<thead class="ui-widget-header">
		<tr>
			<th></th>
			<th>Nro Solicitud</th>
			<th>Nro de Póliza</th>
			<th>Endoso</th>
			<th>Compañia</th>
			<th>Tomador</th>
			<th>Asegurado</th>
			<th>Premio</th>
			<th>Plus</th>
			<th>Fecha Pago</th>
			<th>Moneda</th>
			<th>Cuota</th>
			<th>Importe</th>
		</tr>
	</thead>
	<tbody class="ui-widget-content">
	</tbody>
</table>
</div>
<input type="button" id="realizar_pago" value="Realizar Pago"></input>
<!--  input type="button" id="imprimir_listado_pago" value="Imprimir Listado"></input>-->
<a href='javascript:printContent("div_tabla_polizas")' id='print_link'>Imprimir Listado</a>
	
<div id="realizar_pago_show">
<form id="pago_poliza" name="pago_poliza"
	action="./operaciones/deuda-asegurado/pagar-deuda-asegurado"
	onSubmit="return false"><input type="hidden" id="asegurado_id"
	name="asegurado_id" value="<?=$this->asegurado_id?>"></input>

<h4 id="datos_pago_show">Ingrese los datos del Pago</h4>

<div id="datos_pago">
<table>
	<tr>
		<td>Fecha:</td>
		<td><input id="fecha_pago" value="" name=""></input></td>
	</tr>
	<tr>
		<td>Factura/Recibo:</td>
		<td><input id="numero_factura" value="" name=""></input></td>
	</tr>

	<tr>
		<td>Moneda:</td>
		<td><select id="moneda_id" name="moneda_id">
		<? foreach($this->monedas as $row ):?>
			<option value=<?=$row['dominio_id']?>><?=$row['nombre']?></option>
			<? endforeach; ?>
		</select></td>

</table>

<h4>Efectivo</h4>
<table>
	<tr>
	<td>Importe:</td>
	<td><input value="" id="importe" name="importe"></input></td>
	<td>Descuento:</td>
	<td><input value="" id="descuento" name="descuento"></input></td>
	</tr>
	<tr>
	<td>Cotizaci&oacute;n Divisa:</td>
	<td><input value="" id="cotizacion_divisa" name="cotizacion_divisa"></input></td>
	</tr>
</table>
</div>
<h4 id="div_form_cheques_show">Datos Cheques</h4>
<!--  input type="button" id="add_check" value="+" /> <input type="button"
			id="del_check" value="-" /> <input type="hidden" id="del_check_val"
			value="cheque_1" />-->

<div id="div_form_cheques">
<table id="table_form_cheques">
	<tr>
		<th></th>
	</tr>
	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_0" id="banco_cheque_0"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_0" id="nro_cheque_0" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_0" id="importe_cheque_0"
			value="0"> </input></td>
	</tr>
	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_1" id="banco_cheque_1"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_1" id="nro_cheque_1" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_1" id="importe_cheque_1"
			value="0"> </input></td>
	</tr>
	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_2" id="banco_cheque_2"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_2" id="nro_cheque_2" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_2" id="importe_cheque_2"
			value="0"> </input></td>
	</tr>

	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_3" id="banco_cheque_3"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_3" id="nro_cheque_3" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_3" id="importe_cheque_3"
			value="0"> </input></td>
	</tr>

	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_4" id="banco_cheque_4"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_4" id="nro_cheque_4" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_4" id="importe_cheque_4"
			value="0"> </input></td>
	</tr>

	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_5" id="banco_cheque_5"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_5" id="nro_cheque_5" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_5" id="importe_cheque_5"
			value="0"> </input></td>
	</tr>
</table>
</div>
<input type="submit" value="Confirmar Pago" id="confirmar_pago" />
</div>

<hr>
<div id="resultado_pago">
</div>	

<?if(false):?>
<form id="pago_poliza" name="pago_poliza"
	action="./operaciones/deuda-asegurado/pagar-deuda-asegurado"
	onSubmit="return false"><input type="hidden" id="asegurado_id"
	name="asegurado_id" value="<?=$this->asegurado_id?>"></input>

<h4 id="datos_pago_show">Ingrese los datos del Pago</h4>

<div id="datos_pago">
<table>
	<tr>
		<td>Fecha:</td>
		<td><input id="fecha_pago" value="" name=""></input></td>
	</tr>
	<tr>
		<td>Factura/Recibo:</td>
		<td><input id="numero_factura" value="" name=""></input></td>
	</tr>

	<tr>
		<td>Moneda:</td>
		<td><select id="moneda_id" name="moneda_id">
		<? foreach($this->monedas as $row ):?>
			<option value=<?=$row['dominio_id']?>><?=$row['nombre']?></option>
			<? endforeach; ?>
		</select></td>

</table>

<h4>Efectivo</h4>
<table>
	<td>Importe:</td>
	<td><input value="" id="importe" name="importe"></input></td>
	</tr>
</table>

<h4 id="div_form_cheques_show">Datos Cheques</h4>
<!--  input type="button" id="add_check" value="+" /> <input type="button"
			id="del_check" value="-" /> <input type="hidden" id="del_check_val"
			value="cheque_1" />-->

<div id="div_form_cheques">
<table id="table_form_cheques">
	<tr>
		<th></th>
	</tr>
	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_0" id="banco_cheque_0"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_0" id="nro_cheque_0" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_0" id="importe_cheque_0"
			value="0"> </input></td>
	</tr>
	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_1" id="banco_cheque_1"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_1" id="nro_cheque_1" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_1" id="importe_cheque_1"
			value="0"> </input></td>
	</tr>
	<tr>
		<td>Banco:</td>
		<td><input type="text" name="banco_cheque_2" id="banco_cheque_2"
			value=""> </input></td>
		<td>Nro:</td>
		<td><input type="text" name="nro_cheque_2" id="nro_cheque_2" value="">
		</input></td>
		<td>Importe:</td>
		<td><input type="text" name="importe_cheque_2" id="importe_cheque_2"
			value="0"> </input></td>
	</tr>
</table>
</div>
</div>
<input type="submit" value="Realizar Pago" id="realizar_pago" />
<hr>

<div id="test_inner"><?
/*Asi van a mostrar dos tablas, una para las polizas del tipo caucion
 * Y otra para las polizas comunes
 *
 * Fecha / Vigencia / Nº Solicitud / Nº de Póliza / Endoso / Compañia / TOMADOR
 *  / ASEGURADO
 *  Moneda / Cuota / Importe /
 / DNI  / Estado / Fecha de baja /
 */
?>

<table class="ui-widget">
	<thead class="ui-widget-header">
		<tr>
			<th></th>
			<th>Fecha</th>
			<th>Vigencia</th>
			<th>Nro Solicitud</th>
			<th>Nro de Póliza</th>
			<th>Endoso</th>
			<th>Compañia</th>
			<th>Tomador</th>
			<th>Asegurado</th>
			<th>Premio</th>
			<th>Plus</th>
			<th>Fecha Pago</th>
			<th>Moneda</th>
			<th>Cuota</th>
			<th>Importe</th>
			<th>Despachante</th>
			<th>Cuit</th>
			<th>SIM</th>
			<th>BL</th>
			<th>Factura</th>
			<th>Estado</th>
			<th>Fecha de baja</th>
		</tr>
	</thead>
	<tbody class="ui-widget-content">
	<?
	//1. Primero imprimo las de Aduaneros

	//echo "<pre>";
	//print_r($this->polizas_aduaneros);
	foreach ($this->polizas_aduaneros as $row):
	$d_poliza = new Domain_Poliza($row['poliza_id']);
	$m_poliza = $d_poliza->getModelPoliza();
	$m_detalle_pago = $d_poliza->getModelDetallePago();
	$m_poliza_valores = $d_poliza->getModelPolizaValores();
	$m_poliza_detalle = $d_poliza->getModelDetalle();
	//print_r($m_poliza_detalle);
	$despachante_aduana	=	Domain_DespachanteAduana::getNameById($m_poliza_detalle->despachante_aduana_id)	;
	$asegurado = Domain_Asegurado::getNameById($m_poliza->asegurado_id);
	$moneda = Domain_Helper::getHelperNameById('moneda', $m_detalle_pago->moneda_id);
	$estado_poliza = Domain_EstadoPoliza::getNameById($m_poliza->estado_id);
	?>


	<? $rows = Domain_DetallePago::getCuotas($m_detalle_pago->detalle_pago_id);

	//print_r($row);

	$compania_nombre = Domain_Compania::getNameById($m_poliza->compania_id);
	$fecha_desde = $m_poliza->fecha_vigencia;
	$periodo = $m_poliza->periodo_id;
	//Helper que calcular la fecha de vigencia
	$fecha_hasta = $this->calcularPeriodo($fecha_desde,$periodo);

	$vigencia = $this->traduceFecha($fecha_desde)." hasta ".$this->traduceFecha($fecha_hasta);
	?>

	<?foreach ($rows as $row):

	?>

		<tr>
			<td><input type="checkbox" name="poliza_pago"
				value=<?=$row['detalle_pago_cuota_id']?>
				moneda=<?="$m_detalle_pago->moneda_id"	?>
				importe=<?=$row['importe']?>></input></td>
			<td><?=$m_poliza->fecha_pedido?></td>
			<td><?=$vigencia?></td>
			<td><?=$m_poliza->numero_solicitud?></td>
			<td><?=$m_poliza->numero_poliza?></td>
			<td><?=$m_poliza->endoso?></td>
			<td><?=$compania_nombre ?></td>
			<td><?=$asegurado?></td>
			<td><?=$asegurado?></td>
			<td><?=$m_poliza_valores->premio_asegurado?></td>
			<td><?=$m_poliza_valores->plus?></td>
			<td><?=$row['fecha_pago']?></td>
			<td><?=$moneda?></td>
			<td><?=$row['cuota_id']?></td>
			<td><?=$row['importe']?></td>
			<td><?=$despachante_aduana?></td>
			<td><?//$m_poliza_detalle->cuit?></td>
			<td><?=$m_poliza_detalle->sim?></td>
			<td><?=$m_poliza_detalle->bl?></td>
			<td><?=$m_poliza_detalle->factura?></td>
			<td><?=$estado_poliza?></td>
			<td><?=$m_poliza->fecha_baja?></td>

		</tr>
		<?endforeach;?>


		<?endforeach;?>
	</tbody>
</table>

<!-- Construccion --> <?if(!empty($this->polizas_construccion)):?>
<table class="ui-widget">
	<thead class="ui-widget-header">
		<tr>
			<th></th>
			<th>Fecha</th>
			<th>Vigencia</th>
			<th>Nro Solicitud</th>
			<th>Nro de Póliza</th>
			<th>Endoso</th>
			<th>Compañia</th>
			<th>Tomador</th>
			<th>Asegurado</th>
			<th>Fecha Pago</th>
			<th>Moneda</th>
			<th>Cuota</th>
			<th>Importe</th>
			<th>Estado</th>
			<th>Fecha de baja</th>

		</tr>
	</thead>
	<tbody class="ui-widget-content">
	<?	foreach ($this->polizas_construccion as $row):
	$d_poliza = new Domain_Poliza($row['poliza_id']);
	$m_poliza = $d_poliza->getModelPoliza();
	$m_detalle_pago = $d_poliza->getModelDetallePago();
	$m_poliza_valores = $d_poliza->getModelPolizaValores();
	$m_poliza_detalle = $d_poliza->getModelDetalle();
	//print_r($m_poliza_detalle);

	$asegurado = Domain_Asegurado::getNameById($m_poliza->asegurado_id);
	$moneda = Domain_Helper::getHelperNameById('moneda', $m_detalle_pago->moneda_id);
	$estado_poliza = Domain_EstadoPoliza::getNameById($m_poliza->estado_id);
	?>


	<? $rows = Domain_DetallePago::getCuotas($m_detalle_pago->detalle_pago_id);

	//print_r($row);

	$compania_nombre = Domain_Compania::getNameById($m_poliza->compania_id);
	$fecha_desde = $m_poliza->fecha_vigencia;
	$periodo = $m_poliza->periodo_id;
	//Helper que calcular la fecha de vigencia
	$fecha_hasta = $this->calcularPeriodo($fecha_desde,$periodo);

	$vigencia = $this->traduceFecha($fecha_desde)." hasta ".$this->traduceFecha($fecha_hasta);
	$rows = Domain_DetallePago::getCuotas($m_detalle_pago->detalle_pago_id);
	$compania_nombre = Domain_Compania::getNameById($m_poliza->compania_id);

	?>
	<?foreach ($rows as $row):?>
		<tr>

			<td><input type="checkbox" name="poliza_pago"
				value=<?=$row['detalle_pago_cuota_id']?>
				moneda=<?="$m_detalle_pago->moneda_id"	?>
				importe=<?=$row['importe']?>></input></td>
			<td><?=$m_poliza->fecha_pedido?></td>
			<td><?=$vigencia?></td>
			<td><?=$m_poliza->numero_solicitud?></td>
			<td><?=$m_poliza->numero_poliza?></td>
			<td><?=$m_poliza->endoso?></td>
			<td><?=$compania_nombre ?></td>
			<td><?=$asegurado?></td>
			<td><?=$asegurado?></td>
			<td><?=$row['fecha_pago']?></td>
			<td><?=$moneda?></td>
			<td><?=$row['cuota_id']?></td>
			<td><?=$row['importe']?></td>
			<td><?=$estado_poliza?></td>
			<td><?=$m_poliza->fecha_baja?></td>

		</tr>
		<?endforeach;?>
		<?endforeach;?>
	</tbody>
</table>

<?endif;?> <!-- End Construccion --> <!-- Alquiler --> <?if(!empty($this->polizas_alquiler)):?>
<table class="ui-widget">
	<thead class="ui-widget-header">
		<tr>
			<th></th>
			<th>Fecha</th>
			<th>Vigencia</th>
			<th>Nro Solicitud</th>
			<th>Nro de Póliza</th>
			<th>Endoso</th>
			<th>Compañia</th>
			<th>Tomador</th>
			<th>Asegurado</th>
			<th>Fecha Pago</th>
			<th>Moneda</th>
			<th>Cuota</th>
			<th>Importe</th>
			<th>Estado</th>
			<th>Fecha de baja</th>

		</tr>
	</thead>
	<tbody class="ui-widget-content">
	<?	foreach ($this->polizas_alquiler as $row):
	$d_poliza = new Domain_Poliza($row['poliza_id']);
	$m_poliza = $d_poliza->getModelPoliza();
	$m_detalle_pago = $d_poliza->getModelDetallePago();
	$m_poliza_valores = $d_poliza->getModelPolizaValores();
	$m_poliza_detalle = $d_poliza->getModelDetalle();
	//print_r($m_poliza_detalle);

	$asegurado = Domain_Asegurado::getNameById($m_poliza->asegurado_id);
	$moneda = Domain_Helper::getHelperNameById('moneda', $m_detalle_pago->moneda_id);
	$estado_poliza = Domain_EstadoPoliza::getNameById($m_poliza->estado_id);
	?>


	<? $rows = Domain_DetallePago::getCuotas($m_detalle_pago->detalle_pago_id);

	//print_r($row);

	$compania_nombre = Domain_Compania::getNameById($m_poliza->compania_id);
	$fecha_desde = $m_poliza->fecha_vigencia;
	$periodo = $m_poliza->periodo_id;
	//Helper que calcular la fecha de vigencia
	$fecha_hasta = $this->calcularPeriodo($fecha_desde,$periodo);

	$vigencia = $this->traduceFecha($fecha_desde)." hasta ".$this->traduceFecha($fecha_hasta);
	$rows = Domain_DetallePago::getCuotas($m_detalle_pago->detalle_pago_id);
	$compania_nombre = Domain_Compania::getNameById($m_poliza->compania_id);

	?>
	<?foreach ($rows as $row):?>
		<tr>

			<td><input type="checkbox" name="poliza_pago"
				value=<?=$row['detalle_pago_cuota_id']?>
				moneda=<?="$m_detalle_pago->moneda_id"	?>
				importe=<?=$row['importe']?>></input></td>
			<td><?=$m_poliza->fecha_pedido?></td>
			<td><?=$vigencia?></td>
			<td><?=$m_poliza->numero_solicitud?></td>
			<td><?=$m_poliza->numero_poliza?></td>
			<td><?=$m_poliza->endoso?></td>
			<td><?=$compania_nombre ?></td>
			<td><?=$asegurado?></td>
			<td><?=$asegurado?></td>
			<td><?=$row['fecha_pago']?></td>
			<td><?=$moneda?></td>
			<td><?=$row['cuota_id']?></td>
			<td><?=$row['importe']?></td>
			<td><?=$estado_poliza?></td>
			<td><?=$m_poliza->fecha_baja?></td>

		</tr>
		<?endforeach;?>
		<?endforeach;?>
	</tbody>
</table>

<?endif;?> <!-- End Alquiler --> <!-- Automotor --> <?if(!empty($this->polizas_automotor)):?>
<table class="ui-widget">
	<thead class="ui-widget-header">
		<tr>
			<th></th>
			<th>Fecha</th>
			<th>Vigencia</th>
			<th>Nro Solicitud</th>
			<th>Nro de Póliza</th>
			<th>Endoso</th>
			<th>Compañia</th>
			<th>Tomador</th>
			<th>Asegurado</th>
			<th>Fecha Pago</th>
			<th>Moneda</th>
			<th>Cuota</th>
			<th>Importe</th>
			<th>Estado</th>
			<th>Fecha de baja</th>

		</tr>
	</thead>
	<tbody class="ui-widget-content">
	<?	foreach ($this->polizas_automotor as $row):
	$d_poliza = new Domain_Poliza($row['poliza_id']);
	$m_poliza = $d_poliza->getModelPoliza();
	$m_detalle_pago = $d_poliza->getModelDetallePago();
	$m_poliza_valores = $d_poliza->getModelPolizaValores();
	$m_poliza_detalle = $d_poliza->getModelDetalle();
	//print_r($m_poliza_detalle);

	$asegurado = Domain_Asegurado::getNameById($m_poliza->asegurado_id);
	$moneda = Domain_Helper::getHelperNameById('moneda', $m_detalle_pago->moneda_id);
	$estado_poliza = Domain_EstadoPoliza::getNameById($m_poliza->estado_id);
	?>


	<? $rows = Domain_DetallePago::getCuotas($m_detalle_pago->detalle_pago_id);

	//print_r($row);

	$compania_nombre = Domain_Compania::getNameById($m_poliza->compania_id);
	$fecha_desde = $m_poliza->fecha_vigencia;
	$periodo = $m_poliza->periodo_id;
	//Helper que calcular la fecha de vigencia
	$fecha_hasta = $this->calcularPeriodo($fecha_desde,$periodo);

	$vigencia = $this->traduceFecha($fecha_desde)." hasta ".$this->traduceFecha($fecha_hasta);
	$rows = Domain_DetallePago::getCuotas($m_detalle_pago->detalle_pago_id);
	$compania_nombre = Domain_Compania::getNameById($m_poliza->compania_id);

	?>
	<?foreach ($rows as $row):?>
		<tr>

			<td><input type="checkbox" name="poliza_pago"
				value=<?=$row['detalle_pago_cuota_id']?> /></td>
			<td><?=$m_poliza->fecha_pedido?></td>
			<td><?=$vigencia?></td>
			<td><?=$m_poliza->numero_solicitud?></td>
			<td><?=$m_poliza->numero_poliza?></td>
			<td><?=$m_poliza->endoso?></td>
			<td><?=$compania_nombre ?></td>
			<td><?=$asegurado?></td>
			<td><?=$asegurado?></td>
			<td><?=$row['fecha_pago']?></td>
			<td><?=$moneda?></td>
			<td><?=$row['cuota_id']?></td>
			<td><?=$row['importe']?></td>
			<td><?=$estado_poliza?></td>
			<td><?=$m_poliza->fecha_baja?></td>

		</tr>
		<?endforeach;?>
		<?endforeach;?>
	</tbody>
</table>
		<?endif;?> <input type="button" value="Realizar Pago" /> <input
	type="button" value="Atras" onClick="return listarDeudaAsegurado()" />

</form>

</div>

		<?endif;?>