<<script type="text/javascript">
function listarDeudaAsegurado(){
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');
	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	////console.debug($('#tabs ul li a'));
	var href = $(tab).attr('href') ;
	//console.debug(href);
	//var href_t = href+" #test_inner";
	//console.debug(href_t); 
	//var url = "./poliza/solicitud/confirmar-solicitud";                       
	var url = "./operaciones/deuda-asegurado/list";

	$.ajax({
	    url: url,
    	    success:function(result){
        //console.debug(result);
        $(href).html(result);
      	}
      });
	   
	    return false;


}
</script>
<input type="button" value="Atras" onClick="return listarDeudaAsegurado()"/>
<?php echo "Mostraria si tuvo exito o no y un boton para volver"?>