<script type="text/javascript">
function listPaginator(g){

	var url = $(g).attr('url')
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	//console.debug($('#tabs ul li a'));
	var href = $(tab).attr('href') ;       
	var url = $(g).attr('href')

	    $.ajax({url: url,success:function(result){
	        $(href).html(result);
	      }});
	   
	    return false;
	}

function listCuentaCorriente(f){
	var url = f.action;
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       
	
    $.ajax({url: url,
        data:{
            buscar:f.buscar.value
            ,criterio: f.criterio.value
            }
        , success:function(result){
        $(href).html(result);
      }});
   
    return false;
}


function loadCuentaCorriente(url){
	//var url = f.action;
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       
	/*data:{
            buscar:f.buscar.value
            ,criterio: f.criterio.value
            }*/
    $.ajax({url: url
        
        , success:function(result){
        $(href).html(result);
      }});
   
    return false;
}


</script>


<div id="buscar_asegurado">
<form action="./operaciones/cuenta-corriente/list" onSubmit="return listCuentaCorriente(this)">

	<table id="buscar_asegurado">
		<tr>
			<td><b>Buscar Asegurado:</b></td>
			<td><input type="text" name="criterio" /></td>
			<td><input type="submit" name="buscar" value="buscar"></input></td>
		</tr>
	</table>
</form>
<hr>
</div>
<?if($this->buscar):?>
<table>
  <tr>
    <th>asegurado_id</th>
    <th>Nombre</th>
    <th></th>
  </tr>

<?foreach ($this->rows as $asegurado):?> 
  <tr>
    <td><?=$asegurado['asegurado_id'] ?></td>
    <td><?=$asegurado['nombre']?></td>
    <td><input type="button" value="Ver" onClick="return loadCuentaCorriente('./operaciones/cuenta-corriente/cc-asegurado/asegurado_id/<?=$asegurado['asegurado_id'] ?>')"> </input> </td>
  </tr>
	<?php //onClick="return loadPagePoliza('./operaciones/deuda-asegurado/deuda-asegurado/asegurado_id/<?=$asegurado['asegurado_id'] ?><?//','Deuda-Asegurado')?>
<?endforeach; ?>
</table>
<?endif;?>
<?= $this->paginationControl($this->rows, 'Sliding', 'paginator.phtml',array('criterio'=>$this->criterio)); ?>

