<script type="text/javascript">
function listarProductor(){
	
	url="./entidad/productor/list";

	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       
	
			$.ajax({url: url,
		        success:function(result){
		        $(href).html(result);
		      }});
		   
		    return false;
	}
	
function productor(f){
	var url = $(f).attr('url');
	if(url == null){
		var url="./entidad/productor/list";
	}
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       

	    $.ajax({url: url,success:function(result){
	        $(href).html(result);
	      }});

	    return false;
	}


function editProductor(f){

	var url = f.action;

	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	var href = $(tab).attr('href') ;                       

     $.ajax({url: url,
        data:{
	     id: f.id.value 
	    ,tipo_persona_id: f.tipo_persona_id.value 
            ,nombre: f.nombre.value
            ,matricula: f.matricula.value
            ,cuit: f.cuit.value
            ,domicilio: f.domicilio.value
            ,codigo_postal: f.codigo_postal.value
            ,provincia: f.provincia.value
            ,localidad: f.localidad.value
            ,telefono: f.telefono.value
            ,email: f.email.value
            ,ingresos_brutos: f.ingresos_brutos.value
            ,jubilacion: f.jubilacion.value
            ,situacion_iva: f.situacion_iva.value
            ,situacion_juridica: f.situacion_juridica.value
            }
        , success:function(result){
        $(href).html(result);
      }});
   
   
    return false;
}
</script>



<form action="./entidad/productor/edit" onSubmit="return editProductor(this)">
	<table>
		<tr>
			<td>productor_id</td>
			<td><input type="text" name="id"
				value="<?=$this->row['productor_id']?>"></input></td>
		</tr>
 <td>tipo_persona</td>
                <td><select name="tipo_persona_id">
                                                <? foreach($this->tipo_persona as $row ):?>
                                                <option value=<?=$row['dominio_id']?>>
                                                <?=$row['nombre']?>
                                                </option>
                                                <? endforeach;?>
                                                </select>
                                                </td>
                </tr>

		<tr>
			<td>Nombre</td>
			<td><input type="text" name="nombre"
				value="<?=$this->row['nombre']?>"></input></td>
		</tr>
		<tr>
			<td>Matricula</td>
			<td><input type="text" name="matricula"
				value="<?=$this->row['matricula']?>"></input></td>
		</tr>
		<tr>
			<td>CUIT</td>
			<td><input type="text" name="cuit" value="<?=$this->row['cuit']?>"></input>
			</td>
		</tr>
		<tr>
			<td>Domicilio</td>
			<td><input type="text" name="domicilio"
				value="<?=$this->row['domicilio']?>"></input></td>
		</tr>
		<tr>
			<td>Codigo Postal</td>
			<td><input type="text" name="codigo_postal"
				value="<?=$this->row['codigo_postal']?>"></input></td>
		</tr>
		<tr>
			<td>Provincia</td>
			<td><input type="text" name="provincia"
				value="<?=$this->row['provincia']?>"></input></td>
		</tr>
		<tr>
			<td>Localidad</td>
			<td><input type="text" name="localidad"
				value="<?=$this->row['localidad']?>"></input></td>
		</tr>
		<tr>
			<td>Telefono</td>
			<td><input type="text" name="telefono"
				value="<?=$this->row['telefono']?>"></input></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="email" value="<?=$this->row['email']?>"></input>
			</td>
		</tr>
		<tr>
			<td>Ingresos Brutos</td>
			<td><input type="text" name="ingresos_brutos"
				value="<?=$this->row['ingresos_brutos']?>"></input></td>
		</tr>
		<tr>
			<td>Jubilacion</td>
			<td><input type="text" name="jubilacion"
				value="<?=$this->row['jubilacion']?>"></input></td>
		</tr>
		<tr>
			<td>Situacion Iva</td>
			<td><input type="text" name="situacion_iva"
				value="<?=$this->row['situacion_iva']?>"></input></td>
		</tr>
		<tr>
			<td>Situacion Juridica</td>
			<td><input type="text" name="situacion_juridica"
				value="<?=$this->row['situacion_juridica']?>"></input></td>
		</tr>

		<tr>
			<td></td>
			<td><input type="submit" value="guardar"></input></td>
			<td><input type="button" name="Cancel" onclick="return listarProductor()"
				value="cancel" /></input></td>
		</tr>
	</table>
</form>
