<?php echo $this->headScript()->appendFile('./js/gseguros.poliza.poliza.endoso-poliza-responsabilidad-civil.js');?>

<div id="content">

	<fieldset>
		<legend>Endoso Responsabilidad Civil</legend>


		<form id="endoso_poliza_responsabilidad_civil" name="endoso_poliza"
			action="./poliza/poliza/alta-responsabilidad_civil" onSubmit="return false">
			<input type="hidden" name="save" value=1>
			
			
			<input type="hidden" id="poliza_endoso_id"
				name="poliza_id"
				value="<?=$this->escape($this->poliza_endoso_id)?>" />

			<h3 id="datos_poliza_responsabilidad_civil_show">Datos de la poliza</h3>

			<div id="datos_poliza_responsabilidad_civil">
				<table>
						<tr>
				<td>Tipo de Endoso:</td>
						<td><select id="tipo_responsabilidad_civil_endoso" name="tipo_endoso_id" >
								
								<? foreach($this->tipo_endoso as $row ):?>
								<?if($this->poliza->tipo_endoso_id==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								</option>
								<? endforeach; ?>
						</select>
						</td>
				</tr>
					<tr>
						<td>Número de Solicitud:</td>
						<td><?=$this->escape($this->poliza->numero_solicitud)?></td>

					</tr>
					<tr>
						<td>Número de poliza:</td>
						<td><input type="text" name="numero_poliza"
							value="<?=$this->escape($this->poliza->numero_poliza)?>" /></td>
						<td>Endoso:</td>
						<td><?=$this->escape($this->poliza->endoso)?></td>	
						<td>Tipo:</td>
						<td><?=$this->escape($this->tipo_endoso_text)?></td>	
					</tr>

					<tr>
						<td>Cliente:</td>
						<td><?=$this->escape($this->asegurado)?></td>
					</tr>
					<tr>
						<td>Ejecutivo de Cuentas:</td>

						<td><?=$this->escape($this->agente)?>
						</td>

					</tr>
					<tr>
						<td>Compania Aseguradora:</td>
						<td><?=$this->compania?>
						</td>
					</tr>
					<tr>
						<td>Productor:</td>
						<td><?=$this->productor?>
						</td>
					</tr>
					<tr>
						<td>Cobrador:</td>
						<td><?=$this->cobrador?>
						</td>
					</tr>
				</table>
			</div>
			<hr>
			<h3 id="datos_seguro_responsabilidad_civil_show">Datos del Seguro</h3>
			<div id="datos_seguro">
				<table>
					<tr>
						<td>Fecha de pedido:</td>
						<td><?if($this->isAgente):?> <input readonly type="text"
							id="fecha_pedido_agente" name="fecha_pedido"
							value="<?=$this->poliza->fecha_pedido?>" />
						</td>
						<?else:?>
						<input type="text" id="fecha_pedido" name="fecha_pedido"
							value="<?=$this->poliza->fecha_pedido?>" />
						</td>
						<?endif;?>
					</tr>
				
					<tr>
						<td>Fecha Vigencia:</td>
						<td><input type="text" id="fecha_vigencia" name="fecha_vigencia"
							value="<?=$this->poliza->fecha_vigencia?>" />
						</td>
					</tr>

					<tr>
						<td>Periodo:</td>
						<td><select id="periodo_id" name="periodo_id">
								<option value="0">Seleccione periodo</option>
								<? foreach($this->periodos as $row ):?>
								<?if($this->poliza->periodo_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<!--  tr>
						<td>Plan Comision:</td>
						<td><select name="plan_comision">
								<option value="0">Seleccione Plan</option>
						</select>
						</td>
					<tr>-->
				</table>
			</div>
			<!-- - Nº de licitacion - Obra - Expediente - Objeto - Apertura licitación
- Clausula especial - Certificaciones

5b.- En Construcción
Fila 1: Tipo de Garantia
Fila 2: Motivo de la Garantia
Fila 3: Beneficiario
Luego el resto ordenando en 2 columnas
 -->
			<hr>
			<h3 id="detalle_riesgo_responsabilidad_civil_show">Detalle del Riesgo</h3>
			<div id="detalle_riesgo_responsabilidad_civil">
				<table>
					<tr>
						<td>Tipo de Garantia:</td>
						<td><select id="tipo_garantia_responsabilidad_civil_id"
							name="tipo_garantia_id">
								<option value="0">Seleccione Tipo Garantia</option>
								<? foreach($this->tipo_garantias as $row ):?>
								<?if($this->poliza_detalle->tipo_garantia_id==$row['t_garantia_id']):?>
								<option selected value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Motivo de Garantia:</td>
						<td><select id="motivo_garantia_responsabilidad_civil_id"
							name="motivo_garantia_id">
								<option value="0">Seleccione Motivo Garantia</option>
								<? foreach($this->motivo_garantias as $row ):?>
								<?if($this->poliza_detalle->motivo_garantia_id==$row['motivo_garantia_id']):?>
								<option selected value=<?=$row['motivo_garantia_id']?>>
								<?=$row['motivo_garantia']?>
								<?else:?>
								
								<option value=<?=$row['motivo_garantia_id']?>>
								<?=$row['motivo_garantia']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>

					</tr>

					<tr>
						<td>Beneficiario:</td>
						<td><select id="beneficiario_responsabilidad_civil_id"
							name="beneficiario_id">
								<option value="0">Seleccione Beneficiario</option>
								<? foreach($this->beneficiarios as $row ):?>
								<?if($this->poliza_detalle->beneficiario_id==$row['beneficiario_id']):?>
								<option selected value=<?=$row['beneficiario_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['beneficiario_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>

					</tr>
					<tr>
						<td>Domicilio Riesgo:</td>
						<td><input type="text" id="domicilio_riesgo_responsabilidad_civil"
							name="domicilio_riesgo"
							value="<?=$this->escape($this->poliza_detalle->domicilio_riesgo)?>" />
						</td>

						<td>Localidad Riesgo:</td>
						<td><input type="text" id="localidad_riesgo_responsabilidad_civil"
							name="localidad_riesgo"
							value="<?=$this->escape($this->poliza_detalle->localidad_riesgo)?>" />
						</td>
					</tr>
					<tr>
						<td>Provincia Riesgo:</td>
						<td><input type="text" id="provincia_riesgo_responsabilidad_civil"
							name="provincia_riesgo"
							value="<?=$this->escape($this->poliza_detalle->provincia_riesgo)?>" />
						</td>

					</tr>
					
					<tr>
						<td>Obra:</td>
						<td><textarea id="obra_responsabilidad_civil" name="obra">

							<?=$this->escape($this->poliza_detalle->obra)?>
						</textarea>
						</td>
						<td>Expediente:</td>
						<td><input type="text" id="expediente_responsabilidad_civil" name="expediente"
							value="<?=$this->escape($this->poliza_detalle->expediente)?>" />
						</td>
					</tr>
					<tr>
						<td>Clausula Especial:</td>
						<td><input type="text" id="clausula_especial_responsabilidad_civil"
							name="clausula_especial"
							value="<?=$this->escape($this->poliza_detalle->clausula_especial)?>" />
						</td>
						<td>Personal:</td>
						<td><input type="text" id="personal_responsabilidad_civil"
							name="personal"
							value="<?=$this->escape($this->poliza_detalle->personal)?>" />
						</td>
					</tr>
					<tr>
					<td>Presupuesto Oficial:</td>
						<td><input type="text" id="presupuesto_oficial_responsabilidad_civil"
							name="presupuesto_oficial"
							value="<?=$this->escape($this->poliza_detalle->presupuesto_oficial)?>" />
						</td>
						<td>Descripcion Adicional:</td>
						<td><input type="text" id="descripcion_adicional_responsabilidad_civil"
							name="descripcion_adicional"
							value="<?=$this->escape($this->poliza_detalle->descripcion_adicional)?>" />
						</td>
					</tr>

				</table>
			</div>

			<hr>
			<h3 id="valores_seguro_responsabilidad_civil_show">Valores del seguro</h3>
			<div id="valores_seguro_responsabilidad_civil">
				<table>
		
					<tr>
						<td>Forma de Pago:</td>
					</tr>
					<tr id="forma_pago">
						<td>Pago:</td>
						<td><?=$this->forma_pago?>
						</td>
					</tr>
					<tr id="endoso_cuotas_responsabilidad_civil">
						<td>Cuotas:</td>
						<td><select id="cuotas_responsabilidad_civil_endoso" name="cuotas">
								
								<? foreach($this->cuotas as $row ):?>

								<?if($this->cantidad_cuotas==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								</option>
								<? endforeach; ?>
						</select>
						</td>
						<td>Valor Cuota:</td>
						<td><input id="valor_cuota_responsabilidad_civil_endoso" name="valor_cuota"
							value=<?=$this->escape($this->valor_cuotas)?>>
						</td>
					</tr>
					<tr>
						<td>Monto Asegurado:</td>
						<td><input  type="text" name="monto_asegurado"
							value="<?=$this->escape($this->poliza_valores->monto_asegurado)?>" />
						</td>
					</tr>
					<tr>
						<td>Moneda:</td>
						<td><?=$this->moneda?>
						</td>
					</tr>
					<tr>
						<td>Iva:</td>
						<td><input type="text" name="iva"
							value="<?=$this->escape($this->poliza_valores->iva)?>" /></td>
					</tr>
					<tr>
						<td>Prima:</td>
						<td><input type="text" name="prima_comision"
							value="<?=$this->escape($this->poliza_valores->prima_comision)?>" />
						</td>
					</tr>

					<tr>
						<td>Premio Compania:</td>
						<td><input type="text" name="premio_compania" id="premio_compania"
							value="<?=$this->escape($this->poliza_valores->premio_compania)?>" />
						</td>

					</tr>

					<tr>
						<td>Premio Asegurado:</td>
						<td><input type="text" name="premio_asegurado"
							id="premio_asegurado_endoso"
							value="<?=$this->escape($this->poliza_valores->premio_asegurado)?>" />
						</td>
					</tr>
					<tr>
						<td>Plus:</td>
						<td><input type="text" name="plus" id="plus_endoso"
							value="<?=$this->escape($this->poliza_valores->plus)?>" /></td>
					</tr>
					<tr>
						<td>Importe total a cobrar:</td>
						<td><input readonly type="text" name="importe"
							id="importe_responsabilidad_civil_endoso" value=<?=$this->importe?>></input>
						</td>
					</tr>
					
				</table>	 
			</div>
			<hr>
			<h3 id="observaciones_seguro_responsabilidad_civil_show">Observaciones</h3>
			<div id="observaciones_seguro_responsabilidad_civil">
				<table>

					<tr>
						<td>Asegurado:</td>
						<td><textarea name="observaciones_asegurado">
						<?=$this->escape($this->poliza->observaciones_asegurado)?>
						</textarea>
						</td>
					</tr>
					<tr>
						<td>Compania</td>
						<td><textarea name="observaciones_compania">
						<?=$this->escape($this->poliza->observaciones_compania)?>
						</textarea>
						</td>
					</tr>
				</table>


			</div>


<hr>
			<div id="show_result"></div>
			
<?//pregunto si es operador, si no, no hace nada?>
	<?if($this->operador):?>
			<input type="submit" name="save_endoso_poliza_responsabilidad_civil" id="save_endoso_poliza_responsabilidad_civil" value="Solicitud Endoso Poliza"></input>
			
			
<?if($this->poliza_endoso_id):?>
			<input type="submit" name="enviar_compania_endoso_poliza_responsabilidad_civil" id="enviar_compania_endoso_poliza_responsabilidad_civil" value="Enviar email a Compania "></input>
<?endif;?>
			<input type="button" name="Cancel" onclick="" value="Cancelar" />

		<?endif;?>
	</fieldset>
</div>

