<?php echo $this->headScript()->appendFile('./js/gseguros.poliza.poliza.endoso-poliza-integral-comercio.js');?>
<div id="content">

	<fieldset>
		<legend>Poliza Alquiler</legend>
		<form id="endoso_poliza_integral_comercio" name="endoso_poliza_integral_comercio"
			
			onSubmit="return false">
			<input type="hidden" name="save" value=1>
			<input type="hidden" id="poliza_endoso_id"
				name="poliza_id"
				value="<?=$this->escape($this->poliza_endoso_id)?>" />

			<h3 id="datos_poliza_poliza_show">Datos de la Poliza</h3>
			<div id="datos_poliza_poliza">

				<table>
					<td>Tipo de Endoso:</td>
						<td><select id="tipo_integral_comercio_endoso" name="tipo_endoso_id" >
								
								<? foreach($this->tipo_endoso as $row ):?>
								<?if($this->poliza->tipo_endoso_id==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								</option>
								<? endforeach; ?>
						</select>
						</td>
				</tr>
					<tr>
						<td>Número de Solicitud:</td>
						<td><?=$this->escape($this->poliza->numero_solicitud)?></td>

					</tr>
					<tr>
						<td>Número de poliza:</td>
						<td><input type="text" name="numero_poliza"
							value="<?=$this->escape($this->poliza->numero_poliza)?>" /></td>
					</tr>

					<tr>
						<td>Cliente:</td>
						<td><?=$this->escape($this->asegurado)?></td>
					</tr>
					<tr>
						<td>Ejecutivo de Cuentas:</td>

						<td><?=$this->escape($this->agente)?>
						</td>

					</tr>
					<tr>
						<td>Compania Aseguradora:</td>
						<td><?=$this->compania?>
						</td>
					</tr>
					<tr>
						<td>Productor:</td>
						<td><?=$this->productor?>
						</td>
					</tr>
					<tr>
						<td>Cobrador:</td>
						<td><?=$this->cobrador?>
						</td>
					</tr>
				</table>
			</div>
			<hr>
			<h3 id="datos_seguro_show">Datos del Seguro</h3>
			<div id="datos_seguro">
				<table>
					<tr>
						<td>Fecha de pedido:</td>
						<td><?if($this->isAgente):?> <input readonly type="text"
							id="fecha_pedido_agente_poliza" name="fecha_pedido"
							value="<?=$this->escape($this->poliza->fecha_pedido)?>" />
						</td>
						<?else:?>
						<input readonly type="text" id="fecha_pedido_poliza"
							name="fecha_pedido"
							value="<?=$this->escape($this->poliza->fecha_pedido)?>" />
						</td>
						<?endif;?>
					</tr>
					<tr>
						<td>Fecha Vigencia:</td>
						<?if($this->isAgente): ?>
						<td><input readonly type="text" id="fecha_vigencia_agente_poliza"
							name="fecha_vigencia"
							value="<?=$this->escape($this->poliza->fecha_vigencia)?>" />
						</td>
						<?else:?>
						<td><input readonly type="text" id="fecha_vigencia_poliza_integral_comercio"
							name="fecha_vigencia"
							value="<?=$this->escape($this->poliza->fecha_vigencia)?>" />
						</td>
						<?endif; ?>
					</tr>

					<tr>
						<td>Periodo:</td>
						<td><?=$this->periodo?>
						</td>
					</tr>

				</table>
			</div>
			<!-- `detalle_integral_comercio_id`, `tipo_garantia_id`, `motivo_garantia_id`, `domicilio_riesgo`,
 `localidad_riesgo`, `provincia_riesgo`, `acreedor_prendario`, `mercaderia`, 
 `descripcion_adicional`, `bl`, `factura`, `sim` -->
			<hr>
			<h3 id="detalle_riesgo_integral_comercio_show">Detalle del Riesgo</h3>
			<div id="detalle_riesgo_integral_comercio">
				<table>
					<tr>
						<td>Tipo de Garantia:</td>
						<td><?=$this->tipo_garantia?></td>
					</tr>
					<tr>	
						<td>Motivo de Garantia:</td>
						<td><?=$this->motivo_garantia?></td>
					</tr>


					<tr>
					
						
						<td>Domicilio Riesgo:</td>
						<td><?=$this->escape($this->poliza_detalle->domicilio_riesgo)?> 
						</td>

						<td>Localidad Riesgo:</td>
						<td><?=$this->escape($this->poliza_detalle->localidad_riesgo)?>
						</td>
</tr>
<tr>
						<td>Provincia Riesgo:</td>
						<td><?=$this->escape($this->poliza_detalle->provincia_riesgo)?>
						</td>
						<td>Descripcion Adicional:</td>
						<td><?=$this->escape($this->poliza_detalle->descripcion_adicional)?>
						</td>
					</tr>
					

				</table>
			</div>


			<hr>
			<h3 id="valores_seguro_integral_comercio_show">Valores del seguro</h3>
			<div id="valores_seguro_integral_comercio">
				<table>
					<tr>
						<td>Forma de Pago:</td>
					</tr>
					<tr id="forma_pago">
						<td>Pago:</td>
						<td><?=$this->forma_pago?>
						</td>
					</tr>
					<tr id="endoso_cuotas_integral_comercio">
						<td>Cuotas:</td>
						<td><select id="cuotas_integral_comercio_endoso" name="cuotas">
								
								<? foreach($this->cuotas as $row ):?>

								<?if($this->cantidad_cuotas==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								</option>
								<? endforeach; ?>
						</select>
						</td>
						<td>Valor Cuota:</td>
						<td><input id="valor_cuota_integral_comercio_endoso" name="valor_cuota"
							value=<?=$this->escape($this->valor_cuotas)?>>
						</td>
					</tr>
					<tr>
						<td>Monto Asegurado:</td>
						<td><input  type="text" name="monto_asegurado"
							value="<?=$this->escape($this->poliza_valores->monto_asegurado)?>" />
						</td>
					</tr>
					<tr>
						<td>Moneda:</td>
						<td><?=$this->moneda?>
						</td>
					</tr>
					<tr>
						<td>Iva:</td>
						<td><input type="text" name="iva"
							value="<?=$this->escape($this->poliza_valores->iva)?>" /></td>
					</tr>
					<tr>
						<td>Prima:</td>
						<td><input type="text" name="prima_comision"
							value="<?=$this->escape($this->poliza_valores->prima_comision)?>" />
						</td>
					</tr>

					<tr>
						<td>Premio Compania:</td>
						<td><input type="text" name="premio_compania" id="premio_compania"
							value="<?=$this->escape($this->poliza_valores->premio_compania)?>" />
						</td>

					</tr>

					<tr>
						<td>Premio Asegurado:</td>
						<td><input type="text" name="premio_asegurado"
							id="premio_asegurado"
							value="<?=$this->escape($this->poliza_valores->premio_asegurado)?>" />
						</td>
					</tr>
					<tr>
						<td>Plus:</td>
						<td><input type="text" name="plus" id="plus"
							value="<?=$this->escape($this->poliza_valores->plus)?>" /></td>
					</tr>
					<tr>
						<td>Importe total a cobrar:</td>
						<td><input readonly type="text" name="importe"
							id="importe_integral_comercio_endoso" value=<?=$this->importe?>></input>
						</td>
					</tr>
					
				</table>
			</div>
			<hr>
			<h3 id="observaciones_seguro_integral_comercio_show">Observaciones</h3>
			<div id="observaciones_seguro_integral_comercio">
				<table>

					<tr>
						<td>Asegurado:</td>
						<td><textarea name="observaciones_asegurado">
						<?=$this->escape($this->poliza->observaciones_asegurado)?>
						</textarea></td>
					</tr>
					<tr>
						<td>Compania</td>
						<td><textarea name="observaciones_compania">
						<?=$this->escape($this->poliza->observaciones_compania)?>
						</textarea></td>
					</tr>
							<tr>

						<td>Documentacion</td>

						<td><select name="documentacion_id">
						<? foreach($this->documentacion as $row ):?>

						<?if($this->poliza_detalle->documentacion_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?else:?>
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					
				</table>


			</div>


			<hr>

		<?if($this->operador):?>
			<input type="submit" name="save_endoso_poliza_integral_comercio" id="save_endoso_poliza_integral_comercio" value="Endosar Poliza"></input>

			<input type="button" name="Cancel" onclick="" value="Cancelar" />

		<?endif;?>
		</form>
	</fieldset>
</div>
