<?php echo $this->headScript()->appendFile('./js/gseguros.poliza.poliza.view-poliza-accidentes-personales.js');?>
<div id="content">

	<fieldset>
		<legend>Poliza Accidentes Personales</legend>

			<form id="poliza_poliza_accidentes_personales" name="poliza_poliza"
			action="./poliza/poliza/view-poliza-accidentes-personales"
			onSubmit="return false">
			<input type="hidden" name="save" value=1>
			<input type="hidden"
				name="poliza_id"
				value="<?=$this->escape($this->poliza->poliza_id)?>" />

			<h3 id="datos_poliza_accidentes_personales_show">Datos de la Solicitud</h3>
			<div id="datos_poliza_accidentes_personales">
					<table>
					<tr>
						<td>Número de Solicitud:</td>
						<td><?=$this->escape($this->poliza->numero_solicitud)?></td>

					<?if($this->renovada):?>
					<td>Renueva Poliza Nro:</td>
					<td>
						<?=$this->poliza_renovada_numero_poliza?>
					</td>
					<?endif;?>
					</tr>
					<tr>
						<td>Número de poliza:</td>
						<td><input type="text" name="numero_poliza"
							value="<?=$this->escape($this->poliza->numero_poliza)?>" /></td>
							<td>Endoso:</td>
						<td><?=$this->escape($this->poliza->endoso)?></td>	
						<td>Tipo:</td>
						<td><?=$this->escape($this->tipo_endoso_text)?></td>
					</tr>
					<tr>
						<td>Número de factura:</td>
						<td><input type="text" name="numero_factura"
							value="<?=$this->escape($this->poliza->numero_factura)?>" /></td>
					</tr>

					<tr>
						<td>Cliente:</td>
						<td><?=$this->escape($this->asegurado)?></td>
					</tr>
					<tr>
						<td>Ejecutivo de Cuentas:</td>

						<td><?=$this->escape($this->agente)?>
						</td>

					</tr>
					<tr>
						<td>Compania Aseguradora:</td>
						<td><?=$this->compania?>
						</td>
					</tr>
					<tr>
						<td>Productor:</td>
						<td><?=$this->productor?>
						</td>
					</tr>
					<tr>
						<td>Cobrador:</td>
						<td><?=$this->cobrador?>
						</td>
					</tr>
				</table>
			</div>
			<hr>
			<h3 id="datos_seguro_accidentes_personales_show">Datos del Seguro</h3>
			<div id="datos_seguro_accidentes_personales">
				<table>
					<tr>
						<td>Fecha de pedido:</td>
						<td><?if($this->isAgente):?> <input readonly type="text"
							id="fecha_pedido_agente_poliza" name="fecha_pedido"
							value="<?=$this->escape($this->poliza->fecha_pedido)?>" />
						</td>
						<?else:?>
						<input readonly type="text" id="fecha_pedido_poliza"
							name="fecha_pedido"
							value="<?=$this->escape($this->poliza->fecha_pedido)?>" />
						</td>
						<?endif;?>
					</tr>
					<tr>
						<td>Fecha Vigencia:</td>
						<?if($this->isAgente): ?>
						<td><input readonly type="text" id="fecha_vigencia_agente_poliza"
							name="fecha_vigencia"
							value="<?=$this->escape($this->poliza->fecha_vigencia)?>" />
						</td>
						<?else:?>
						<td><input readonly type="text"
							id="fecha_vigencia_poliza_accidentes_personales" name="fecha_vigencia"
							value="<?=$this->escape($this->poliza->fecha_vigencia)?>" />
						</td>
						<?endif; ?>
					</tr>

					<tr>
						<td>Periodo:</td>
						<td><?=$this->periodo?>
						</td>
					</tr>

				</table>
			</div>	
<!-- Detalle del Riesgo  -->

<hr>
			<h3 id="detalle_riesgo_accidentes_personales_show">Detalle del Riesgo</h3>
			<div id="detalle_riesgo_accidentes_personales">
				<table>
					<tr>
						<td>Tipo de Seguro:</td>
						<td><?=$this->tipo_garantia?></td>
					</tr>
					<tr>
						<td>Tipo de Cobertura:</td>
						<td><?=$this->motivo_garantia?></td>
					</tr>
				
					<tr>
					<tr>
						<td>Beneficiario:</td>
						<td><?=$this->escape($this->beneficiario)?>	</td>
						<td>Domicilio Riesgo:</td>
						
					</tr>
				<!-- Cantidad de personas a asegurar,Tareas a realizar,Altura máxima de los trabajos -->	
					
					<tr>
						<td>Cantidad de Personas:</td>
						<td><?=$this->escape($this->poliza_detalle->cantidad_personas)?>
						</td>

						<td>Tareas a realizar:</td>
						<td><?=$this->escape($this->poliza_detalle->tareas_a_realizar)?>
						</td>
						</tr>
					<tr>
						<td>Altura M&aacute;xima:</td>
						<td><?=$this->escape($this->poliza_detalle->altura_maxima)?>
						</td>
					</tr>
					<tr>
						<td>Datos Asegurados:</td>
						<td><?=$this->escape($this->poliza_detalle->datos_adicionales)?>
						</input>
						</td>
					</tr>

				</table>
			</div>
			
<!-- FIN Detalle del Riesgo -->
			<hr>
			<h3 id="valores_seguro_accidentes_personales_show">Valores del seguro</h3>
			<div id="valores_seguro_accidentes_personales">
				<table>
					<tr>
						<td>Forma de Pago:</td>
					</tr>
					<tr id="forma_pago">
						<td>Pago:</td>
						<td><?=$this->forma_pago?>
						</td>
					</tr>
					<tr id="view_cuotas_accidentes_personales">
						<td>Cuotas:</td>
						<td><?=$this->cantidad_cuotas?>
						</td>
						<td>Valor Cuota:</td>
						<td><input readonly id="view_valor_cuota_accidentes_personales"
							name="valor_cuota" value="<?=$this->valor_cuotas ?>"></td>
					</tr>
					<tr>
						<td>Monto Asegurado:</td>
						<td><input  type="text" name="monto_asegurado"
							value="<?=$this->escape($this->poliza_valores->monto_asegurado)?>" />
						</td>
					</tr>
					<tr>
						<td>Moneda:</td>
						<td><?=$this->moneda?>
						</td>
					</tr>
					<tr>
						<td>Iva:</td>
						<td><input type="text" name="iva"
							value="<?=$this->escape($this->poliza_valores->iva)?>" /></td>
					</tr>
					<tr>
						<td>Prima:</td>
						<td><input type="text" name="prima_comision"
							value="<?=$this->escape($this->poliza_valores->prima_comision)?>" />
						</td>
					</tr>

					<tr>
						<td>Premio Compania:</td>
						<td><input type="text" name="premio_compania" id="premio_compania"
							value="<?=$this->escape($this->poliza_valores->premio_compania)?>" />
						</td>

					</tr>

					<tr>
						<td>Premio Asegurado:</td>
						<td><input type="text" name="premio_asegurado"
							id="premio_asegurado"
							value="<?=$this->escape($this->poliza_valores->premio_asegurado)?>" />
						</td>
					</tr>
					<tr>
						<td>Plus:</td>
						<td><input type="text" name="plus" id="plus"
							value="<?=$this->escape($this->poliza_valores->plus)?>" /></td>
					</tr>
					<tr>
						<td>Importe:</td>
						<td><input readonly type="text" id="importe"
							value=<?=$this->importe?> /></td>
					</tr>

				</table>
			</div>
<hr>

			<h3 id="observaciones_seguro_accidentes_personales_show">Observaciones</h3>
			<div id="observaciones_seguro_accidentes_personales">
				<table>

					<tr>
						<td>Asegurado:</td>
						<td><textarea name="observaciones_asegurado">
						<?=$this->escape($this->poliza->observaciones_asegurado)?>
						</textarea></td>
					</tr>
					<tr>
						<td>Compania</td>
						<td><textarea name="observaciones_compania">
						<?=$this->escape($this->poliza->observaciones_compania)?>
						</textarea></td>
					</tr>
					
					<tr>

						<td>Documentacion</td>

						<td><select name="documentacion_id">
						<? foreach($this->documentacion as $row ):?>

						<?if($this->poliza_detalle->documentacion_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?else:?>
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
				</table>
</div>
			<hr>
			
<?if($this->operador):?>
			<input type="submit" name="save_poliza_accidentes_personales" id="save_poliza_accidentes_personales" value="Guardar Cambios"></input>

			<input type="button" name="Cancel" onclick="" value="Cancelar" />

<?endif;?>
		</form>
	</fieldset>
</div>
