
<script type="text/javascript">

function listUsuario(f){
	
		url="./admin/usuario/list";
		
	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	//console.debug($('#tabs ul li a'));
	var href = $(tab).attr('href') ;                       

	    $.ajax({url: url,success:function(result){
	        $(href).html(result);
	      }});

	    return false;
	}
/*
function addUsuario(f){

	var url = f.action;

	var tabs_sel = $('#tabs').tabs();
	var idx = tabs_sel.tabs('option', 'selected');

	//Trae el tab correspondiente
	var tab = $('#tabs ul li a')[idx];
	//console.debug($('#tabs ul li a'));
	var href = $(tab).attr('href') ;                       
	 $.ajax({url: url,
	        data:{add: f.add.value
	            ,id: f.id.value 
	            ,tipo_usuario_id: f.tipo_usuario_id.value
	            ,usuario_tipo_id: f.usuario_tipo_id.value
	            ,username: f.username.value
	            ,password: f.password.value
	            ,usuario_perfil_id:f.usuario_perfil_id.value
	            }
	        , success:function(result){
	        $(href).html(result);
	      }});
	   
	   
	    return false;
	}
	*/
$(document).ready(function() { 
$("#form_usuario").validate({
    rules: {
        password: {
            required: true,
            minlength: 3
        },
        confirm_password: {
            required: true,
            minlength: 3,
            equalTo: "#password"
        }
    },
    messages: {
    	 password: {
             required: "No puede estar vacio",
             minlength: "Longitud mayor a 3 caracteres"
         },
        confirm_password: {
            required: "confirma el password",
            minlength: "",
            equalTo: "Tiene que ser igual"
        }
    }
});

$("#save_usuario").click(function() {
//alert('clic');
//return false;
	  //alert("Valid: " + $("#alta_usuario").valid());
	var url ="./admin/usuario/password";
	  var username = $( "#username" ),
      password = $( "#password" ),
      usuario_id = $( "#usuario_id" ),
      add_usuario = $("#add_usuario");
      
     // alert(usuario_id.val());
     // return false;
 //Si no es valido devuelve false y me voy del script     
if(!$("#form_usuario").valid())return false;	  

		var tabs_sel = $('#tabs').tabs();
		var idx = tabs_sel.tabs('option', 'selected');

		//Trae el tab correspondiente
		var tab = $('#tabs ul li a')[idx];
		//console.debug($('#tabs ul li a'));
		var href = $(tab).attr('href') ;                       

		
		 $.ajax({url: url,
		        data:{
			        save: true
		            ,id: usuario_id.val() 
		            ,password: password.val()
		            }
		        , success:function(result){
		        $(href).html(result);
		      }});
		   
		    return false;
	});

});

</script>

<?if(!$this->save):?>
<form id="form_usuario" action="#" method="GET">
	 <!-- onSubmit="return addUsuario(this)" -->
	<input type="hidden" value="1" name="save"></input>
	<input type="hidden" name="usuario_id" id="usuario_id" value="<?=$this->usuario_id?>"></input>
	<table>
	
		<tr>
			<td>username</td>
			<td><input readonly type="text" name="username" id="username"
				value="<?=$this->username?>"></input></td>
		</tr>
		<tr>
			<td>password</td>
			<td><input type="password" id="password" id="password" name="password"
				value="<?=$this->row['password']?>"></input></td>
		</tr>
		<tr>
			<td>Confirme password</td>
			<td><input type="password" id="confirm_password" name="confirm_password"
				value="<?=$this->row['password']?>"></input></td>
		</tr>
		<tr>
			<td></td>
			<td><input type="submit" id="save_usuario" value="guardar"></input></td>
			<td><input type="button" name="Cancel" onclick="return listUsuario()"
				value="cancel" /></input></td>
		</tr>
	</table>

</form>
<?else:?>
<input type="button" name="volver" onclick="return listUsuario()"
				value="Volver" /></input>
<?endif; ?>

