<script type="text/javascript">
function listar(){
	
url="./entidad/compania/list";
		$.ajax({url: url,
	        success:function(result){
	        $('#content').html(result);
	      }});
	   
	    return false;
}

function editForm(f){

    var url = f.action;
    $.ajax({url: url,
        data:{
             add:f.add.value
             ,id: f.id.value 
             ,nombre: f.nombre.value
             ,cuit: f.cuit.value
             ,domicilio: f.domicilio.value
             ,codigo_postal: f.codigo_postal.value
             ,provincia: f.provincia.value
             ,localidad: f.localidad.value
             ,telefono: f.telefono.value
             ,email: f.email.value
            }
        , success:function(result){
        $('#content').html(result);
      }});
   
    return false;
}
</script>

<form action="./entidad/compania/add"  onSubmit="return editForm(this)">
<input type="hidden" name="add" value=1></input>
<table>
<tr><td>compania_id</td><td><input type="text" name="id" value=""></input></td></tr>
<tr><td>Nombre</td><td><input type="text" name="nombre" value=""></input></td></tr>
<tr><td>CUIT</td><td><input type="text" name="cuit" value=""></input></td></tr>
<tr><td>Domicilio</td><td><input type="text" name="domicilio" value=""></input></td></tr>
<tr><td>Codigo Postal</td><td><input type="text" name="codigo_postal" value=""></input></td></tr>
<tr><td>Provincia</td><td><input type="text" name="provincia" value=""></input></td></tr>
<tr><td>Localidad</td><td><input type="text" name="localidad" value=""></input></td></tr>
<tr><td>Telefono</td><td><input type="text" name="telefono" value=""></input></td></tr>
<tr><td>Email</td><td><input type="text" name="email" value=""></input></td></tr>
<tr><td></td><td><input type="submit" value="Guardar"></input></td><td><input type="button" name="Cancel" onclick="return listar()" value="cancel" /></input></td></tr>
</table>
</form>