<?php echo $this->headScript()->appendFile('./js/gseguros.poliza.solicitud.alta-accidentes-personales.js');?>
<div id="content">

	<fieldset>
		<legend>Solicitud Accidentes Personales</legend>

			<form id="solicitud_poliza_accidentes_personales" name="solicitud_poliza"
			action="./poliza/solicitud/alta-accidentes-personales"
			onSubmit="return false">
			<input type="hidden" name="save" value=1>

			<h3 id="datos_solicitud_accidentes_personales_show">Datos de la Solicitud</h3>
			<div id="datos_solicitud_accidentes_personales">
				<table>
					<tr>
						<td>Número de solicitud:</td>
						<td><input readonly type="text" name="numero_solicitud"
						id="numero_solicitud"
							value="<?=$this->solicitud->numero_solicitud?>" />
							<input type="hidden" name="solicitud_id"
						id="solicitud_id"
							value="<?=$this->solicitud->poliza_id?>" />
						</td>
					</tr>

					<!-- Autocomplente para Asegurados -->
					<tr>
						<td>Asegurado:</td>
						<?if( empty($this->solicitud->poliza_id) ):?>
						<td><input id="asegurado" type="text" name="asegurado"
							value="<?=$this->solicitud->asegurado_id?>"></input> <input
							type="hidden" id="asegurado_id" name="asegurado_id" value=""></input>
						</td>
						<?else:?>
						<td><input readonly id="asegurado" type="text" name="asegurado"
							value="<?=$this->asegurado_nombre?>"></input> <input
							type="hidden" id="asegurado_id" name="asegurado_id"
							value="<?=$this->solicitud->asegurado_id?>"></input></td>
							<?endif;?>
					</tr>
					<tr>
						<td>Agente:</td>
						<?if($this->isAgente):?>
						<td><?=$this->agente_nombre?> <input name="agente_id"
							value=<?=$this->agente_id?> type="hidden"></input>
						</td>
						<?else:?>
						<td><select name="agente_id">
								<option value="0">Seleccione Agente</option>
								<? foreach($this->agentes as $row ):?>
								<?if($this->solicitud->agente_id==$row['agente_id']):?>
								<option selected value=<?=$row['agente_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['agente_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select> <?endif;?>
						</td>
					</tr>
					<tr>
						<td>Compania Aseguradora:</td>
						<td><select name="compania_id">
								<option value="0">Seleccione Compania</option>
								<? foreach($this->companias as $row ):?>
								<?if($this->solicitud->compania_id==$row['compania_id']):?>
								<option selected value=<?=$row['compania_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['compania_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Productor:</td>
						<td><select name="productor_id">
								<option value="0">Seleccione Productor</option>
								<? foreach($this->productores as $row ):?>
								<?if($this->solicitud->productor_id==$row['productor_id']):?>
								<option selected value=<?=$row['productor_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['productor_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Cobrador:</td>
						<td><select name="cobrador_id">
								<option value="0">Seleccione Cobrador</option>
								<? foreach($this->cobradores as $row ):?>
								<?if($this->solicitud->cobrador_id==$row['cobrador_id']):?>
								<option selected value=<?=$row['cobrador_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['cobrador_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>

						</select>
						</td>
					</tr>
				</table>
			</div>
			<hr>
			<h3 id="datos_seguro_accidentes_personales_show">Datos del Seguro</h3>
			<div id="datos_seguro_accidentes_personales">
				<table>
					<tr>
						<td>Fecha de pedido:</td>
						<td><?if($this->isAgente):?> <input readonly type="text"
							id="fecha_pedido_agente" name="fecha_pedido"
							value="<?=$this->solicitud->fecha_pedido?>" />
						</td>
						<?else:?>
						<input type="text" id="fecha_pedido" name="fecha_pedido"
							value="<?=$this->solicitud->fecha_pedido?>" />
						</td>
						<?endif;?>
					</tr>
					<tr>
						<td>Fecha Vigencia:</td>
						<td><input type="text" id="fecha_vigencia" name="fecha_vigencia"
							value="<?=$this->solicitud->fecha_vigencia?>" />
						</td>
					</tr>

					<tr>
						<td>Periodo:</td>
						<td><select id="periodo_id" name="periodo_id">
								<option value="0">Seleccione periodo</option>
								<? foreach($this->periodos as $row ):?>
								<?if($this->solicitud->periodo_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
				</table>
			</div>	
<!-- Detalle del Riesgo  -->

<hr>
			<h3 id="detalle_riesgo_accidentes_personales_show">Detalle del Riesgo</h3>
			<div id="detalle_riesgo_accidentes_personales">
				<table>
				<tr>
						<td>Tipo de Seguro:</td>
						<!-- tipo_seguro = tipo_garantia -->
						<td><select id="tipo_garantia_id" name="tipo_garantia_id">
								<option value="0">Seleccione Tipo de Seguro</option>
								<? foreach($this->tipo_garantias as $row ):?>
								<?if($this->poliza_detalle->tipo_garantia_id==$row['t_garantia_id']):?>
								<option selected value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								<option value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
					</tr>
					<tr>
						<td>Tipo de Cobertura:</td>
						<!-- tipo_cobertura = motivo_garantia -->
						<td width="471" id="table_motivo_garantia_id">
						<select   id="motivo_garantia_id" name="motivo_garantia_id">
							<option value="0">Seleccione Tipo de Cobertura</option>
							<? foreach($this->motivo_garantias as $row ):?>
							<?if($this->poliza_detalle->motivo_garantia_id==$row['motivo_garantia_id']):?>
							<option selected value=<?=$row['motivo_garantia_id']?>>
							<?=$row['motivo_garantia']?>
							<?else:?>
							
							<option value=<?=$row['motivo_garantia_id']?>>
							<?=$row['motivo_garantia']?>
							</option>
							<?endif; ?>
							<? endforeach; ?>
					</select>
						</td>
					</tr>
				
					<tr>
					<td>Beneficiario:</td>
					<td><select id="beneficiario_id" name="beneficiario_id">
							<option value="0">Seleccione Beneficiario</option>
							<? foreach($this->beneficiarios as $row ):?>
							<?if($this->poliza_detalle->beneficiario_id==$row['beneficiario_id']):?>
							<option selected value=<?=$row['beneficiario_id']?>>
							<?=$row['nombre']?>
							<?else:?>
							
							<option value=<?=$row['beneficiario_id']?>>
							<?=$row['nombre']?>
							</option>
							<?endif; ?>
							<? endforeach; ?>
					</select>
					</td>
					</tr>
				<!-- Cantidad de personas a asegurar,Tareas a realizar,Altura máxima de los trabajos -->	
					
					<tr>
						<td>Cantidad de Personas:</td>
						<td><input type="text" id="cantidad_personas"
							name="cantidad_personas"
							value="<?=$this->escape($this->poliza_detalle->cantidad_personas)?>" />
						</td>

						<td>Tareas a realizar:</td>
						<td><input type="text" id="tareas_a_realizar"
							name="tareas_a_realizar"
							value="<?=$this->escape($this->poliza_detalle->tareas_a_realizar)?>" />
						</td>
						</tr>
					<tr>
						<td>Altura M&aacute;xima:</td>
						<td><input type="text" id="altura_maxima"
							name="altura_maxima"
							value="<?=$this->escape($this->poliza_detalle->altura_maxima)?>" />
						</td>
					</tr>
					<tr>
						<td>Datos Asegurados:</td>
						<td><textarea style="text-align: justify;" rows="4" cols="50" id="datos_adicionales_accidentes_personales" name="datos_adicionales"><?=$this->escape($this->poliza_detalle->datos_adicionales)?></textarea>
						</input>
					</td>
						
					</tr>

				</table>
			</div>
<!-- FIN Detalle del Riesgo -->
			<hr>
			<h3 id="valores_seguro_accidentes_personales_show">Valores del seguro</h3>
			<div id="valores_seguro_accidentes_personales">
				<table>
					<tr>
						<td>Moneda:</td>
						<td><select name="moneda_id">
						<? foreach($this->monedas as $row ):?>
						<?if($this->poliza_valores->moneda_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Monto Asegurado:</td>
						<td><input type="text" name="monto_asegurado" id="monto_asegurado"
							value="<?=$this->escape($this->poliza_valores->monto_asegurado)?>" />
						</td>
						
						<td>Prima:</td>
						<td><input type="text" name="prima"
							value="<?=$this->escape($this->poliza_valores->prima_comision)?>" />
						</td>
					
					</tr>
					<tr id="forma_pago">
						<td>Forma de Pago:</td>
						<td><select name="forma_pago_id" id="forma_pago_id">
						<? foreach($this->forma_pagos as $row ):?>
						<?if($this->detalle_pago->forma_pago_id==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								<? endforeach; ?>
						</select>
						</td>
					
					
					<tr id="datos_tarjeta_show">
						<td>Tipo:</td>
						<td><select>
								<option>VISA</option>
								<option>MASTERCARD</option>
								<option>AMERICAN EXPRESS</option>
								<option>GUILES CARD PREMIUM</option>
						</select>
						</td>
						<td>Numero:</td>
						<td><input value=""></input>
						</td>
						<td>Otros:</td>
						<td><input value=""></input>
						</td>
					</tr>
					<tr>
						<td>Cuotas:</td>
						<td><select id="cuotas_accidentes_personales" name="cuotas">
								
								<? foreach($this->cuotas as $row ):?>

								<?if($this->cantidad_cuotas==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								</option>
								<? endforeach; ?>
						</select>
						</td>
						<td>Valor Cuota:</td>
						<td><input id="valor_cuota_accidentes_personales" name="valor_cuota"
							value=<?=$this->escape($this->valor_cuotas)?>>
						</td>
					</tr>

					<tr>
						<td>Importe total a cobrar:</td>
						<td><input readonly type="text" name="importe" id="importe_accidentes_personales"
							value=<?=$this->importe?> ></input>
						</td>
					</tr>

					<!--  tr>
						<td>Premio Asegurado:</td>
						<td><input type="text" name="premio_asegurado"
							value="<?php //$this->escape($this->poliza_valores->premio_asegurado)?>" /></td>
					</tr>
					<tr>
						<td>Plus:</td>
						<td><input type="text" name="plus"
							value="<?php //$this->escape($this->poliza_valores->plus)?>" /></td>
					</tr>-->
				</table>
			</div>
	<hr>
			<h3 id="observaciones_seguro_aduaneros_show">Observaciones</h3>
			<div id="observaciones_seguro_aduaneros">
				<table>

					<tr>
						<td>Asegurado:</td>
						<td><textarea name="observaciones_asegurado"><?=$this->escape($this->solicitud->observaciones_asegurado)?></textarea>
						</td>
					</tr>
					<tr>
						<td>Compania</td>
						<td><textarea name="observaciones_compania"><?=$this->escape($this->solicitud->observaciones_compania)?></textarea>
						</td>
					</tr>
				</table>


			</div>

			<hr>
			
			<?if($this->isAgente):?>
			<?if(empty($this->solicitud->poliza_id)):?>
			<input type="submit" name="save_solicitud_accidentes_personales"
				id="save_solicitud_accidentes_personales" value="Solicitar"></input>
				<?elseif(!empty($this->solicitud->poliza_id)):?>

			<input type="submit" name="save_solicitud_accidentes_personales"
				id="save_solicitud_accidentes_personales" value="Guardar Cambios"></input>
<?endif;?>
				<?endif;?>
			
<?//pregunto si es operador, si no, no hace nada?>
<?if($this->operador):?>
			<?if(empty($this->solicitud->poliza_id)):?>
			<input type="submit" name="save_solicitud_accidentes_personales" id="save_solicitud_accidentes_personales" value="Solicitar"></input>
			<?elseif(!empty($this->solicitud->poliza_id)):?>

			<input type="submit" name="save_solicitud_accidentes_personales" id="save_solicitud_accidentes_personales" value="Guardar Cambios"></input>
			<?
			$codigo_estado = Domain_EstadoPoliza::getCodigoById($this->solicitud->estado_id);
			switch ($codigo_estado) {
				case 'SOLICITUD_PENDIENTE':?>
				
			<input type='submit' name='aprobar_solicitud_accidentes_personales' id='aprobar_solicitud_accidentes_personales'
				value='Aprobar Solicitud'
				onClick="return false">
			</input>
			
			<input type='submit' name='confirmar_solicitud_accidentes_personales' id='confirmar_solicitud_accidentes_personales'
			 value='Aprobar Solicitud y Crear Poliza'
				onClick="return false"> </input> 
			
			
			<input type='submit'
				name='enviar_compania_solicitud_accidentes_personales' id='enviar_compania_solicitud_accidentes_personales'
				value='Enviar Solicitud Compania' onClick="return false" />
			
			
			<input type='submit'
				name='anular_solicitud_accidentes_personales' id='anular_solicitud_accidentes_personales'
				value='Anular Solicitud' onClick="return false" />
			
		
			<?break;
			case 'SOLICITUD_CONFIRMADA':?>
			<input type='submit' name='confirmar_solicitud_accidentes_personales' id='confirmar_solicitud_accidentes_personales'
				value='Crear Poliza'
				onClick="return false">
			</input>
			
			<input type='submit'
				name='anular_solicitud_accidentes_personales' id='anular_solicitud_accidentes_personales'
				value='Anular Solicitud' onClick="return false" />
			<?break;
		default:

		break;
			}?>


			<?endif;?>
			<input type="button" name="Cancel" onclick="" value="Cancelar" />
<?endif;?>

<div id="show_result">
			
			</div>
		</form>
	</fieldset>
</div>


