<?php echo $this->headScript()->appendFile('./js/gseguros.poliza.solicitud.alta-seguro-tecnico.js');?>
<?php /*

Detalle del Riesgo
- Tipo de Garantia: aqui despliega Obra publica / Obra Privada / Suministro
- Motivo de la Garantia: (aca anoto los que ya están - despues se agregan otros)
Garantia de suministro - Servicio público y privado / Mantenimiento de oferta / Ejecución de contrato /
Anticipo financiero y de acopio / Sustitución de fondo de reparo / Garantía de Adjudicación / Garantía de suministro - Servicio publico y privado

- beneficiario
- domicilio riesgo
- localidad riesgo
- provincia riego

- Nº de licitacion
- Obra
- Expediente
- Objeto
- Apertura licitación

- Clausula especial
- Certificaciones

Descripcion adicionals


*/?>
<div id="content">

	<fieldset>
		<legend>Solicitud Seguro Tecnico</legend>


		<form id="solicitud_poliza_seguro_tecnico" name="solicitud_poliza"
			action="./poliza/solicitud/alta-seguro_tecnico" onSubmit="return false">
			<input type="hidden" name="save" value=1>

			<h3 id="datos_solicitud_seguro_tecnico_show">Datos de la Solicitud</h3>
			<div id="datos_solicitud_seguro_tecnico">
				<table>
					<tr>
						<td>Número de solicitud:</td>
						<td><input readonly type="text" name="numero_solicitud"
							id="numero_solicitud"
							value="<?=$this->solicitud->numero_solicitud?>" /> <input
							type="hidden" name="solicitud_id" id="solicitud_id"
							value="<?=$this->solicitud->poliza_id?>" />
					
					</tr>

					<!-- Autocomplente para Clientes -->
					<tr>
						<td>Cliente:</td>
						<?if( empty($this->solicitud->poliza_id) ):?>
						<td><input id="asegurado" type="text" name="asegurado"
							value="<?=$this->solicitud->asegurado_id?>"></input> <input
							type="hidden" id="asegurado_id" name="asegurado_id" value=""></input>
						</td>
						<?else:?>
						<td><input readonly id="asegurado" type="text" name="asegurado"
							value="<?=$this->asegurado_nombre?>"></input> <input
							type="hidden" id="asegurado_id" name="asegurado_id"
							value="<?=$this->solicitud->asegurado_id?>"></input>
						</td>
						<?endif;?>
					</tr>
					<tr>
						<td>Agente:</td>
						<?if($this->isAgente):?>
						<td><?=$this->agente_nombre?> <input name="agente_id"
							value=<?=$this->agente_id?> type="hidden"></input>
						</td>
						<?else:?>
						<td><select name="agente_id">
								<option value="0">Seleccione Agente</option>
								<? foreach($this->agentes as $row ):?>
								<?if($this->solicitud->agente_id==$row['agente_id']):?>
								<option selected value=<?=$row['agente_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['agente_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select> <?endif;?>
						</td>
					</tr>
					<tr>
						<td>Compania Aseguradora:</td>
						<td><select name="compania_id">
								<option value="0">Seleccione Compania</option>
								<? foreach($this->companias as $row ):?>
								<?if($this->solicitud->compania_id==$row['compania_id']):?>
								<option selected value=<?=$row['compania_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['compania_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Productor:</td>
						<td><select name="productor_id">
								<option value="0">Seleccione Productor</option>
								<? foreach($this->productores as $row ):?>
								<?if($this->solicitud->productor_id==$row['productor_id']):?>
								<option selected value=<?=$row['productor_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['productor_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Cobrador:</td>
						<td><select name="cobrador_id">
								<option value="0">Seleccione Cobrador</option>
								<? foreach($this->cobradores as $row ):?>
								<?if($this->solicitud->cobrador_id==$row['cobrador_id']):?>
								<option selected value=<?=$row['cobrador_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['cobrador_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>

						</select>
						</td>
					</tr>
				</table>
			</div>
			<hr>
			<h3 id="datos_seguro_seguro_tecnico_show">Datos del Seguro</h3>
			<div id="datos_seguro">
				<table>
					<tr>
						<td>Fecha de pedido:</td>
						<td><?if($this->isAgente):?> <input readonly type="text"
							id="fecha_pedido_agente" name="fecha_pedido"
							value="<?=$this->solicitud->fecha_pedido?>" />
						</td>
						<?else:?>
						<input type="text" id="fecha_pedido" name="fecha_pedido"
							value="<?=$this->solicitud->fecha_pedido?>" />
						</td>
						<?endif;?>
					</tr>
					<!--  tr>
						<td>Seguimiento:</td>
						<td><select name="tipo_poliza_id">
								<option value="0">Seleccione tipo</option>
						</select>
						</td>
					</tr>-->

					<tr>
						<td>Fecha Vigencia:</td>
						<td><input type="text" id="fecha_vigencia" name="fecha_vigencia"
							value="<?=$this->solicitud->fecha_vigencia?>" />
						</td>
					</tr>

					<tr>
						<td>Periodo:</td>
						<td><select id="periodo_id" name="periodo_id">
								<option value="0">Seleccione periodo</option>
								<? foreach($this->periodos as $row ):?>
								<?if($this->solicitud->periodo_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<!--  tr>
						<td>Plan Comision:</td>
						<td><select name="plan_comision">
								<option value="0">Seleccione Plan</option>
						</select>
						</td>
					<tr>-->
				</table>
			</div>
			<!-- - Nº de licitacion - Obra - Expediente - Objeto - Apertura licitación
- Clausula especial - Certificaciones

5b.- En Construcción
Fila 1: Tipo de Garantia
Fila 2: Motivo de la Garantia
Fila 3: Beneficiario
Luego el resto ordenando en 2 columnas
 -->
			<hr>
			<h3 id="detalle_riesgo_seguro_tecnico_show">Detalle del Riesgo</h3>
			<div id="detalle_riesgo_seguro_tecnico">
				<table>
					<tr>
						<td>Tipo de Garantia:</td>
						<td><select id="tipo_garantia_id" name="tipo_garantia_id">
								<option value="0">Seleccione Tipo Garantia</option>
								<? foreach($this->tipo_garantias as $row ):?>
								<?if($this->poliza_detalle->tipo_garantia_id==$row['t_garantia_id']):?>
								<option selected value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Motivo de Garantia:</td>
						<td><select id="motivo_garantia_id" name="motivo_garantia_id">
								<option value="0">Seleccione Motivo Garantia</option>
								<? foreach($this->motivo_garantias as $row ):?>
								<?if($this->poliza_detalle->motivo_garantia_id==$row['motivo_garantia_id']):?>
								<option selected value=<?=$row['motivo_garantia_id']?>>
								<?=$row['motivo_garantia']?>
								<?else:?>
								
								<option value=<?=$row['motivo_garantia_id']?>>
								<?=$row['motivo_garantia']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>

					</tr>

					<tr>
						<td>Beneficiario:</td>
						<td><select id="beneficiario_id" name="beneficiario_id">
								<option value="0">Seleccione Beneficiario</option>
								<? foreach($this->beneficiarios as $row ):?>
								<?if($this->poliza_detalle->beneficiario_id==$row['beneficiario_id']):?>
								<option selected value=<?=$row['beneficiario_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['beneficiario_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>

					</tr>
					<tr>
						<td>Domicilio Riesgo:</td>
						<td><input type="text" id="domicilio_riesgo"
							name="domicilio_riesgo"
							value="<?=$this->escape($this->poliza_detalle->domicilio_riesgo)?>" />
						</td>

						<td>Localidad Riesgo:</td>
						<td><input type="text" id="localidad_riesgo"
							name="localidad_riesgo"
							value="<?=$this->escape($this->poliza_detalle->localidad_riesgo)?>" />
						</td>
					</tr>
					<tr>
						<td>Provincia Riesgo:</td>
						<td><input type="text" id="provincia_riesgo"
							name="provincia_riesgo"
							value="<?=$this->escape($this->poliza_detalle->provincia_riesgo)?>" />
						</td>

						<!-- - Nº de licitacion - Obra - Expediente - Objeto - Apertura licitación
- Clausula especial - Certificaciones
 -->
						<td>Nro de licitacion:</td>
						<td><input type="text" id="numero_licitacion"
							name="numero_licitacion"
							value="<?=$this->escape($this->poliza_detalle->numero_licitacion)?>" />
						</td>
					</tr>
					<tr>
						<td>Obra:</td>
						<td><textarea id="obra" name="obra">
						<?=$this->escape($this->poliza_detalle->obra)?>
						</textarea>
						</td>
						<td>Expediente:</td>
						<td><input type="text" id="expediente" name="expediente"
							value="<?=$this->escape($this->poliza_detalle->expediente)?>" />
						</td>
					</tr>

					<tr>
						<td>Objeto:</td>
						<td><textarea id="objeto" name="objeto">
							<?=$this->escape($this->poliza_detalle->objeto)?>
						</textarea>
						</td>
						<td>Apertura Licitacion:</td>
						<td><input type="text" id="apertura_licitacion"
							name="apertura_licitacion"
							value="<?=$this->escape($this->poliza_detalle->apertura_licitacion)?>" />
						</td>
					</tr>
					<tr>
						<td>Clausula Especial:</td>
						<td> <textarea style="width: 400px; height: 350px;" id="clausula_especial" name="clausula_especial"><?=$this->escape($this->poliza_detalle->clausula_especial)?></textarea>
						</td>
						<td>Certificaciones:</td>
						<td><input type="text" id="certificaciones" name="certificaciones"
							value="<?=$this->escape($this->poliza_detalle->certificaciones)?>" />
						</td>

					</tr>
					<tr>
						<td>Descripcion Adicional:</td>
						<td><input type="text" id="descripcion_adicional"
							name="descripcion_adicional"
							value="<?=$this->escape($this->poliza_detalle->descripcion_adicional)?>" />
						</td>
					</tr>

				</table>
			</div>


			<hr>
			<h3 id="valores_seguro_seguro_tecnico_show">Valores del seguro</h3>
			<div id="valores_seguro_seguro_tecnico">
				<table>
					<tr>
						<td>Moneda:</td>
						<td><select name="moneda_id">
						<? foreach($this->monedas as $row ):?>
						<?if($this->poliza_valores->moneda_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Monto Asegurado:</td>
						<td><input type="text" name="monto_asegurado" id="monto_asegurado"
							value="<?=$this->escape($this->poliza_valores->monto_asegurado)?>" />
						</td>
						<td>Prima:</td>
						<td><input type="text" name="prima"
							value="<?=$this->escape($this->poliza_valores->prima_comision)?>" />
						</td>
					</tr>
					<tr id="forma_pago">
						<td>Forma de Pago:</td>
						<td><select name="forma_pago_id" id="forma_pago_id">
						<? foreach($this->forma_pagos as $row ):?>
						<?if($this->detalle_pago->forma_pago_id==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								<? endforeach; ?>
						</select>
						</td>
					
					
					<tr id="datos_tarjeta_show">
						<td>Tipo:</td>
						<td><select>
								<option>VISA</option>
								<option>MASTERCARD</option>
								<option>AMERICAN EXPRESS</option>
								<option>GUILES CARD PREMIUM</option>
						</select>
						</td>
						<td>Numero:</td>
						<td><input value=""></input>
						</td>
						<td>Otros:</td>
						<td><input value=""></input>
						</td>
					</tr>
					<tr>
						<td>Cuotas:</td>
						<td><select id="cuotas_seguro_tecnico" name="cuotas">

						<? foreach($this->cuotas as $row ):?>

						<?if($this->cantidad_cuotas==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								</option>
								<? endforeach; ?>
						</select>
						</td>
						<td>Valor Cuota:</td>
						<td><input id="valor_cuota_seguro_tecnico" name="valor_cuota"
							value=<?=$this->escape($this->valor_cuotas)?>>
						</td>
					</tr>

					<tr>
						<td>Importe total a cobrar:</td>
						<td><input readonly type="text" name="importe"
							id="importe_seguro_tecnico" value=<?=$this->importe?>></input>
						</td>
					</tr>

					<!--  tr>
						<td>Premio Asegurado:</td>
						<td><input type="text" name="premio_asegurado"
							value="<?php //$this->escape($this->poliza_valores->premio_asegurado)?>" /></td>
					</tr>
					<tr>
						<td>Plus:</td>
						<td><input type="text" name="plus"
							value="<?php //$this->escape($this->poliza_valores->plus)?>" /></td>
					</tr>-->
				</table>
			</div>
			<hr>
			<h3 id="observaciones_seguro_seguro_tecnico_show">Observaciones</h3>
			<div id="observaciones_seguro_seguro_tecnico">
				<table>

					<tr>
						<td>Asegurado:</td>
						<td><textarea name="observaciones_asegurado">
						<?=$this->escape($this->solicitud->observaciones_asegurado)?>
						</textarea>
						</td>
					</tr>
					<tr>
						<td>Compania</td>
						<td><textarea name="observaciones_compania">
						<?=$this->escape($this->solicitud->observaciones_compania)?>
						</textarea>
						</td>
					</tr>
				</table>


			</div>


			<hr>
			<?if($this->isAgente):?>
			<?if(empty($this->solicitud->poliza_id)):?>
			<input type="submit" name="save_solicitud_seguro_tecnico"
				id="save_solicitud_seguro_tecnico" value="Solicitar"></input>
				<?elseif(!empty($this->solicitud->poliza_id)):?>

			<input type="submit" name="save_solicitud_seguro_tecnico"
				id="save_solicitud_seguro_tecnico" value="Guardar Cambios"></input>
<?endif;?>
				<?endif;?>

				<?if($this->operador):?>
				<?if(empty($this->solicitud->poliza_id)):?>
			<input type="submit" name="save_solicitud_seguro_tecnico"
				id="save_solicitud_seguro_tecnico" value="Solicitar"></input>
				<?elseif(!empty($this->solicitud->poliza_id)):?>

			<input type="submit" name="save_solicitud_seguro_tecnico"
				id="save_solicitud_seguro_tecnico" value="Guardar Cambios"></input>
				<?
				$codigo_estado = Domain_EstadoPoliza::getCodigoById($this->solicitud->estado_id);
				switch ($codigo_estado) {
					case 'SOLICITUD_PENDIENTE':?>

			<input type='submit' name='aprobar_solicitud_seguro_tecnico'
				id='aprobar_solicitud_seguro_tecnico' value='Aprobar Solicitud'
				onClick="return false"> </input> 
				
				<input type='submit'
				name='confirmar_solicitud_seguro_tecnico'
				id='confirmar_solicitud_seguro_tecnico'
				value='Aprobar Solicitud y Crear Poliza' onClick="return false"> </input>

<input type='submit'
				name='enviar_compania_solicitud_seguro_tecnico' id='enviar_compania_solicitud_seguro_tecnico'
				value='Enviar Solicitud Compania' onClick="return false" />
			
			<input type='submit' name='anular_solicitud_seguro_tecnico'
				id='anular_solicitud_seguro_tecnico' value='Anular Solicitud'
				onClick="return false" />


				<?break;
case 'SOLICITUD_CONFIRMADA':?>
			<input type='submit' name='confirmar_solicitud_seguro_tecnico'
				id='confirmar_solicitud_seguro_tecnico' value='Crear Poliza'
				onClick="return false"> </input> <input type='submit'
				name='anular_solicitud_seguro_tecnico'
				id='anular_solicitud_seguro_tecnico' value='Anular Solicitud'
				onClick="return false" />
				<?break;
default:

	break;
				}?>


				<?endif;?>
			<input type="button" name="Cancel" onclick="" value="Cancelar" />


			<?endif;?>

		</form>
		
		<div id="show_result">
			
			</div>
		
	</fieldset>
	
</div>

