<?php //Por ahora usamos este js pero deberia crear uno nuevo 
echo $this->headScript()->appendFile('./js/gseguros.poliza.solicitud.renovacion-judiciales.js');?>

<div id="content">

	<fieldset>
		<legend>Renovacion Judiciales</legend>

		<form id="solicitud_poliza_judiciales"
			name="solicitud_poliza"
			action="./poliza/solicitud/renovacion-judiciales"
			onSubmit="return false">
			<input type="hidden" name="save" value=1>

			<h3 id="datos_solicitud_judiciales_show">Datos de la
				Solicitud</h3>
			<div id="datos_solicitud_judiciales">
				<table>
				<tr>
				<td>P&oacute;liza a Renovar:</td><td><?=$this->numero_poliza?> / <?=$this->endoso?></td>
				</tr>
					<tr>
						<td>Número de solicitud:</td>
						<td><input readonly type="text" name="numero_solicitud"
							id="numero_solicitud_judiciales"
							value="<?=$this->numero_solicitud?>" /> 
							<input
							type="hidden" name="poliza_id"
							id="solicitud_judiciales_id"
							value="<?=$this->poliza_id?>" />
							<input
							type="hidden" name="poliza_renovada_id"
							id="solicitud_renovada_judiciales_id"
							value="<?=$this->solicitud_renovada?>" />
						</td>
					</tr>

					<!-- Autocomplente para Clientes -->
					<tr>
						<td>Cliente:</td>
						
						<td><input readonly id="asegurado_judiciales"
							type="text" name="asegurado" value="<?=$this->asegurado_nombre?>"></input>
							<input type="hidden" id="asegurado_judiciales_id"
							name="asegurado_id" value="<?=$this->solicitud->asegurado_id?>"></input>
						</td>
						
					</tr>
					<tr>
						<td>Agente:</td>
						<?if($this->isAgente):?>
						<td><?=$this->agente_nombre?> <input name="agente_id"
							value=<?=$this->agente_id?> type="hidden"></input>
						</td>
						<?else:?>
						<td><select name="agente_id">
								<option value="0">Seleccione Agente</option>
								<? foreach($this->agentes as $row ):?>
								<?if($this->solicitud->agente_id==$row['agente_id']):?>
								<option selected value=<?=$row['agente_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['agente_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select> <?endif;?>
						</td>
					</tr>
					<tr>
						<td>Compania Aseguradora:</td>
						<td><select name="compania_id">
								<option value="0">Seleccione Compania</option>
								<? foreach($this->companias as $row ):?>
								<?if($this->solicitud->compania_id==$row['compania_id']):?>
								<option selected value=<?=$row['compania_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['compania_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Productor:</td>
						<td><select name="productor_id">
								<option value="0">Seleccione Productor</option>
								<? foreach($this->productores as $row ):?>
								<?if($this->solicitud->productor_id==$row['productor_id']):?>
								<option selected value=<?=$row['productor_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['productor_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Cobrador:</td>
						<td><select name="cobrador_id">
								<option value="0">Seleccione Cobrador</option>
								<? foreach($this->cobradores as $row ):?>
								<?if($this->solicitud->cobrador_id==$row['cobrador_id']):?>
								<option selected value=<?=$row['cobrador_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['cobrador_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>

						</select>
						</td>
					</tr>
				</table>
			</div>
			<hr>
			<h3 id="datos_seguro_judiciales_show">Datos del Seguro</h3>
			<div id="datos_seguro_judiciales">
				<table>
					<tr>
						<td>Fecha de pedido:</td>
						<td><?if($this->isAgente):?> <input readonly type="text"
							id="fecha_pedido_agente_judiciales"
							name="fecha_pedido" value="<?=Domain_Util::today()?>" />
						</td>
						<?else:?>
						<td>
						<input type="text" id="fecha_pedido_judiciales"
							name="fecha_pedido" value="<?=Domain_Util::today()?>" />
						</td>
						<?endif;?>
					</tr>
					<!--  tr>
						<td>Seguimiento:</td>
						<td><select name="tipo_poliza_id">
								<option value="0">Seleccione tipo</option>
						</select>
						</td>
					</tr>-->

					<tr>
						<td>Fecha Vigencia:</td>
						<td><input type="text" id="fecha_vigencia_judiciales"
							name="fecha_vigencia"
							value="<?=Domain_Util::today()?>" />
						</td>
					</tr>

					<tr>
						<td>Periodo:</td>
						<td><select id="periodo_judiciales_id"
							name="periodo_id">
								<option value="0">Seleccione periodo</option>
								<? foreach($this->periodos as $row ):?>
								<?if($this->solicitud->periodo_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>

				</table>
			</div>

			<!-- 
			Detalle del Riesgo
- Tipo de Garantia - Motivo de la Garantia: - Beneficiario - Domicilio riesgo - Localidad riesgo - Provincia riesgo
- Obra - Expediente - Clausula especial - Descripcion adicional
			 -->
			<hr>
			<h3 id="detalle_riesgo_construccion_show">Detalle del Riesgo</h3>
			<div id="detalle_riesgo_construccion">
				<table>
					<tr>
						<td>Tipo de Garantia:</td>
						<td><select id="tipo_garantia_id" name="tipo_garantia_id">
								<option value="0">Seleccione Tipo Garantia</option>
								<? foreach($this->tipo_garantias as $row ):?>
								<?if($this->poliza_detalle->tipo_garantia_id==$row['t_garantia_id']):?>
								<option selected value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['t_garantia_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Motivo de Garantia:</td>
						<td><select id="motivo_garantia_id" name="motivo_garantia_id">
								<option value="0">Seleccione Motivo Garantia</option>
								<? foreach($this->motivo_garantias as $row ):?>
								<?if($this->poliza_detalle->motivo_garantia_id==$row['motivo_garantia_id']):?>
								<option selected value=<?=$row['motivo_garantia_id']?>>
								<?=$row['motivo_garantia']?>
								<?else:?>
								
								<option value=<?=$row['motivo_garantia_id']?>>
								<?=$row['motivo_garantia']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>

					</tr>

					<tr>
						<td>Beneficiario:</td>
						<td><select id="beneficiario_id" name="beneficiario_id">
								<option value="0">Seleccione Beneficiario</option>
								<? foreach($this->beneficiarios as $row ):?>
								<?if($this->poliza_detalle->beneficiario_id==$row['beneficiario_id']):?>
								<option selected value=<?=$row['beneficiario_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['beneficiario_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>

					</tr>
					<tr>
						<td>Domicilio Riesgo:</td>
						<td><input type="text" id="domicilio_riesgo"
							name="domicilio_riesgo"
							value="<?=$this->escape($this->poliza_detalle->domicilio_riesgo)?>" />
						</td>

						<td>Localidad Riesgo:</td>
						<td><input type="text" id="localidad_riesgo"
							name="localidad_riesgo"
							value="<?=$this->escape($this->poliza_detalle->localidad_riesgo)?>" />
						</td>
					</tr>
					<tr>
						<td>Provincia Riesgo:</td>
						<td><input type="text" id="provincia_riesgo"
							name="provincia_riesgo"
							value="<?=$this->escape($this->poliza_detalle->provincia_riesgo)?>" />
						</td>

						<!-- - Nº de licitacion - Obra - Expediente - Objeto - Apertura licitación
- Clausula especial - Certificaciones
 -->
						<td>Nro de licitacion:</td>
						<td><input type="text" id="numero_licitacion"
							name="numero_licitacion"
							value="<?=$this->escape($this->poliza_detalle->numero_licitacion)?>" />
						</td>
					</tr>
					<tr>
						<td>Obra:</td>
						<td><textarea id="obra" name="obra">
						<?=$this->escape($this->poliza_detalle->obra)?>
						</textarea>
						</td>
						<td>Expediente:</td>
						<td><input type="text" id="expediente" name="expediente"
							value="<?=$this->escape($this->poliza_detalle->expediente)?>" />
						</td>
					</tr>

					<tr>
						<td>Objeto:</td>
						<td><textarea id="objeto" name="objeto">
							<?=$this->escape($this->poliza_detalle->objeto)?>
						</textarea>
						</td>
						<td>Apertura Licitacion:</td>
						<td><input type="text" id="apertura_licitacion"
							name="apertura_licitacion"
							value="<?=$this->escape($this->poliza_detalle->apertura_licitacion)?>" />
						</td>
					</tr>
					<tr>
						<td>Clausula Especial:</td>
						<td> <textarea  id="clausula_especial" name="clausula_especial">
							<?=$this->escape($this->poliza_detalle->clausula_especial)?>
						</textarea>
						</td>
						<td>Certificaciones:</td>
						<td><input type="text" id="certificaciones" name="certificaciones"
							value="<?=$this->escape($this->poliza_detalle->certificaciones)?>" />
						</td>

					</tr>
					<tr>
						<td>Descripcion Adicional:</td>
						<td><input type="text" id="descripcion_adicional"
							name="descripcion_adicional"
							value="<?=$this->escape($this->poliza_detalle->descripcion_adicional)?>" />
						</td>
					</tr>

				</table>
			</div>




			<hr>
			<h3 id="valores_seguro_judiciales_show">Valores del seguro</h3>
			<div id="valores_seguro_judiciales">
				<table>
					<tr>
						<td>Moneda:</td>
						<td><select name="moneda_id">
						<? foreach($this->monedas as $row ):?>
						<?if($this->poliza_valores->moneda_id==$row['dominio_id']):?>
								<option selected value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else:?>
								
								<option value=<?=$row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif; ?>
								<? endforeach; ?>
						</select>
						</td>
					</tr>
					<tr>
						<td>Monto Asegurado:</td>
						<td><input type="text" name="monto_asegurado" id="monto_asegurado"
							value="<?=$this->escape($this->poliza_valores->monto_asegurado)?>" />
						</td>

						<td>Prima:</td>
						<td><input type="text" name="prima"
							value="<?=$this->escape($this->poliza_valores->prima_comision)?>" />
						</td>

					</tr>
					<tr id="forma_pago">
						<td>Forma de Pago:</td>
						<td><select name="forma_pago_id" id="forma_pago_judiciales_id">
						<? foreach($this->forma_pagos as $row ):?>
						<?if($this->detalle_pago->forma_pago_id==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								<? endforeach; ?>
						</select>
						</td>
					
					
					<tr id="datos_tarjeta_judiciales_show">
						<td>Tipo:</td>
						<td><select>
								<option>VISA</option>
								<option>MASTERCARD</option>
								<option>AMERICAN EXPRESS</option>
								<option>GUILES CARD PREMIUM</option>
						</select>
						</td>
						<td>Numero:</td>
						<td><input value=""></input>
						</td>
						<td>Otros:</td>
						<td><input value=""></input>
						</td>
					</tr>
					<tr>
						<td>Cuotas:</td>
						<td><select id="cuotas_judiciales" name="cuotas">

						<? foreach($this->cuotas as $row ):?>

						<?if($this->cantidad_cuotas==$row['dominio_id']):?>
								<option selected value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								<?else: ?>
								
								<option value=<?= $row['dominio_id']?>>
								<?=$row['nombre']?>
								</option>
								<?endif;?>
								</option>
								<? endforeach; ?>
						</select>
						</td>
						<td>Valor Cuota:</td>
						<td><input id="valor_cuota_judiciales"
							name="valor_cuota" value=<?=$this->escape($this->valor_cuotas)?>>
						</td>
					</tr>

					<tr>
						<td>Importe total a cobrar:</td>
						<td><input readonly type="text" name="importe"
							id="importe_judiciales" value=<?=$this->importe?>></input>
						</td>
					</tr>

				</table>
			</div>
			<hr>
			<h3 id="observaciones_seguro_judiciales_show">Observaciones</h3>
			<div id="observaciones_seguro_judiciales">
				<table>

					<tr>
						<td>Asegurado:</td>
						<td><textarea name="observaciones_asegurado">
						<?=$this->escape($this->solicitud->observaciones_asegurado)?>
						</textarea>
						</td>
					</tr>
					<tr>
						<td>Compania</td>
						<td><textarea name="observaciones_compania">
						<?=$this->escape($this->solicitud->observaciones_compania)?>
						</textarea>
						</td>
					</tr>
				</table>


			</div>
			<hr>

			<?if($this->isAgente):?>
			<?if(empty($this->solicitud->poliza_id)):?>
			<input type="submit" name="save_solicitud_judiciales"
				id="save_solicitud_judiciales" value="Solicitar"></input>
				<?elseif(!empty($this->solicitud->poliza_id)):?>

			<input type="submit" name="save_solicitud_judiciales"
				id="save_solicitud_judiciales" value="Guardar Cambios"></input>
				<?endif;?>
				<?endif;?>

				<?//pregunto si es operador, si no, no hace nada?>
				<?if($this->operador):?>
				<?if(empty($this->poliza_id)):?>
			<input type="submit" name="save_solicitud_judiciales"
				id="save_solicitud_judiciales" value="Solicitar"></input>
				<?elseif(!empty($this->poliza_id)):?>

			<input type="submit" name="save_solicitud_judiciales"
				id="save_solicitud_judiciales" value="Guardar Cambios"></input>
				<?
				$codigo_estado = Domain_EstadoPoliza::getCodigoById($this->solicitud->estado_id);
				switch ($codigo_estado) {
					case 'SOLICITUD_PENDIENTE':?>

			<input type='submit' name='aprobar_solicitud_judiciales'
				id='aprobar_solicitud_judiciales' value='Aprobar Solicitud'
				onClick="return false"> </input> <input type='submit'
				name='confirmar_solicitud_judiciales'
				id='confirmar_solicitud_judiciales'
				value='Aprobar Solicitud y Crear Poliza' onClick="return false"> </input>

			<input type='submit' name='anular_solicitud_judiciales'
				id='anular_solicitud_judiciales' value='Anular Solicitud'
				onClick="return false" />


				<?break;
case 'SOLICITUD_CONFIRMADA':?>
			<input type='submit' name='confirmar_solicitud_judiciales'
				id='confirmar_solicitud_judiciales' value='Crear Poliza'
				onClick="return false"> </input> <input type='submit'
				name='anular_solicitud_judiciales' id='anular_solicitud_judiciales'
				value='Anular Solicitud' onClick="return false" />
				<?break;
default:

	break;
				}?>


				<?endif;?>
			<input type="button" name="Cancel" onclick="" value="Cancelar" />
			<?endif;?>



		</form>
	</fieldset>
</div>

